/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Bussiness.Resume;
import Bussiness.ResumeHistory;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static sun.net.www.http.HttpClient.New;


/**
 *
 * @author Eric
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private ResumeHistory rehis;
//    Resume resume = rehis.addResume();
    
    public CreateJPanel(ResumeHistory rehis) {
        initComponents();
        
        ImageJLable.setBorder(BorderFactory.createLineBorder(Color.black));
        
        BtnGroup_Gender.add(MaleRBtn);
        BtnGroup_Gender.add(FemaleRBtn);
        BtnGroup_Nation.add(CitizenRBtn);
        BtnGroup_Nation.add(InternationalRBtn);
        BtnGroup_Status1.add(Graduate1RBtn);
        BtnGroup_Status1.add(InPro1RBtn);
        BtnGroup_Status2.add(Graduate2RBtn);
        BtnGroup_Status2.add(InPro2RBtn);
        MaleRBtn.setSelected(true);
        CitizenRBtn.setSelected(true);
        Graduate1RBtn.setSelected(true);
        Graduate2RBtn.setSelected(true);
        
        this.rehis = rehis;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup_Gender = new javax.swing.ButtonGroup();
        BtnGroup_Nation = new javax.swing.ButtonGroup();
        BtnGroup_Status1 = new javax.swing.ButtonGroup();
        BtnGroup_Status2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        CreateCoverPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EmailTextF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MobileTextF = new javax.swing.JTextField();
        MonthBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        AffilTextF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddressTextF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AptTextF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CityTextF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Major1TextF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ZipTextF = new javax.swing.JTextField();
        StateBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Degree1Box = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Core1TextF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        InstructionTextF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        LevelBox = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatementTextArea = new javax.swing.JTextArea();
        CreateBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        UploadBtn = new javax.swing.JButton();
        ImageJLable = new javax.swing.JLabel();
        YearBox = new javax.swing.JComboBox<>();
        DateBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        FemaleRBtn = new javax.swing.JRadioButton();
        MaleRBtn = new javax.swing.JRadioButton();
        CitizenRBtn = new javax.swing.JRadioButton();
        InternationalRBtn = new javax.swing.JRadioButton();
        Graduate1RBtn = new javax.swing.JRadioButton();
        InPro1RBtn = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        Degree2Box = new javax.swing.JComboBox<>();
        Major2TextF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Graduate2RBtn = new javax.swing.JRadioButton();
        InPro2RBtn = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        Core2TextF = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        JavaCheck = new javax.swing.JCheckBox();
        CplusCheck = new javax.swing.JCheckBox();
        PhpCheck = new javax.swing.JCheckBox();
        SqlCheck = new javax.swing.JCheckBox();
        FnameTextF = new javax.swing.JTextField();
        LnameTextF = new javax.swing.JTextField();
        PathTextF = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setText("Create New Resume");

        jLabel2.setText("FirstName:");

        jLabel3.setText("LastName:");

        jLabel4.setText("Gender:");

        jLabel5.setText("BirthDate:");

        jLabel9.setText("Mobile:");

        jLabel10.setText("E-mail:");

        MonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        MonthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Affiliation:");

        jLabel12.setText("Address:");

        jLabel13.setText("Apt:");

        jLabel14.setText("City:");

        jLabel15.setText("State:");

        jLabel16.setText("Zipcode:");

        StateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AK", "AZ", "CA", "CD", "FL", "GA", "IN", "MA", "MS", "NV", "PA", "WY" }));

        jLabel17.setText("Degree:");

        Degree1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "Bachelor", "Master", "PhD", "MBA", "DBA", "Others" }));

        jLabel18.setText("Major:");

        jLabel19.setText("Core Course:");

        jLabel21.setText("Skills:");

        jLabel22.setText("Level:");

        LevelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Beginner", "Familiar", "Good", "Master" }));

        jLabel23.setText("Make Your Personal Statement:");

        StatementTextArea.setColumns(20);
        StatementTextArea.setRows(5);
        jScrollPane2.setViewportView(StatementTextArea);

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        UploadBtn.setText("Upload Photo");
        UploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadBtnActionPerformed(evt);
            }
        });

        ImageJLable.setBackground(new java.awt.Color(255, 255, 255));
        ImageJLable.setSize(new java.awt.Dimension(50, 50));

        YearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        DateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel24.setText("Nation:");

        jLabel27.setText("Instructions:");

        FemaleRBtn.setText("Female");
        FemaleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRBtnActionPerformed(evt);
            }
        });

        MaleRBtn.setText("Male");

        CitizenRBtn.setText("Citizen");

        InternationalRBtn.setText("International");

        Graduate1RBtn.setText("Graduated");

        InPro1RBtn.setText("In Progress ");

        jLabel20.setText("Degree:");

        Degree2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "Bachelor", "Master", "PhD", "MBA", "DBA", "Others" }));

        jLabel29.setText("Major:");

        Graduate2RBtn.setText("Graduated");

        InPro2RBtn.setText("In Progress ");

        jLabel30.setText("Core Course:");

        JavaCheck.setText("JAVA");

        CplusCheck.setText("C++");

        PhpCheck.setText("PHP");

        SqlCheck.setText("SQL");

        PathTextF.setEnabled(false);

        javax.swing.GroupLayout CreateCoverPanelLayout = new javax.swing.GroupLayout(CreateCoverPanel);
        CreateCoverPanel.setLayout(CreateCoverPanelLayout);
        CreateCoverPanelLayout.setHorizontalGroup(
            CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(Core1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(Degree1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Major1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Graduate1RBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InPro1RBtn))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(Core2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(Degree2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Major2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Graduate2RBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InPro2RBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel24)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CitizenRBtn)
                                            .addComponent(MaleRBtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FemaleRBtn)
                                            .addComponent(InternationalRBtn)))
                                    .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(PathTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createSequentialGroup()
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UploadBtn)
                                    .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76))))))
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                            .addGap(428, 428, 428)
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LevelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InstructionTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(JavaCheck)
                                .addGap(18, 18, 18)
                                .addComponent(CplusCheck)
                                .addGap(18, 18, 18)
                                .addComponent(PhpCheck)
                                .addGap(18, 18, 18)
                                .addComponent(SqlCheck))
                            .addComponent(jLabel23)))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(CreateBtn)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        CreateCoverPanelLayout.setVerticalGroup(
            CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(FnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MaleRBtn)
                            .addComponent(FemaleRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CitizenRBtn)
                            .addComponent(InternationalRBtn)
                            .addComponent(jLabel24))
                        .addGap(11, 11, 11)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addComponent(PathTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Degree1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(Major1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Graduate1RBtn)
                    .addComponent(InPro1RBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Core1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Degree2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(Major2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Graduate2RBtn)
                    .addComponent(InPro2RBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Core2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(JavaCheck)
                    .addComponent(CplusCheck)
                    .addComponent(PhpCheck)
                    .addComponent(SqlCheck)
                    .addComponent(jLabel22)
                    .addComponent(LevelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(InstructionTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(CreateCoverPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MonthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthBoxActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
                
        try
        {
            if(FnameTextF.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Insert Your FirstName!");
            }else if(LnameTextF.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Insert Your LastName!");
            }else
            {   
                try
                {
                int zip = Integer.parseInt(ZipTextF.getText());

                }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null,"Insert Right Zipcode!");
                }
                
                try
                {
                    int mobile = Integer.parseInt(MobileTextF.getText());
                }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null,"Insert Right Phone Number!");
                }
                
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Error!");
        }
        
        Resume resume = rehis.addResume();
        
        try
        {   
            resume.setFirstname(FnameTextF.getText());
            resume.setLastname(LnameTextF.getText());
            resume.setAffiliation(AffilTextF.getText());
            
            if(BtnGroup_Gender.getSelection().equals(MaleRBtn.getModel()))
            {
                resume.setGender("Male");
            }else if (BtnGroup_Gender.getSelection().equals(FemaleRBtn.getModel()))
            {
                resume.setGender("Female");
            }
            
            if(BtnGroup_Nation.getSelection().equals(CitizenRBtn.getModel()))
            {
                resume.setNation("Citizen");
            }else if (BtnGroup_Nation.getSelection().equals(InternationalRBtn.getModel()))
            {
                resume.setNation("International");
            }
            
            resume.setBirthday_year(YearBox.getSelectedItem().toString());
            resume.setBirthday_month(MonthBox.getSelectedItem().toString());
            resume.setBirthday_date(DateBox.getSelectedItem().toString());
            resume.setImage(PathTextF.getText());
//            System.out.println(resume.getImage());
            
            resume.setAddress(AddressTextF.getText());
            resume.setApt(AptTextF.getText());
            resume.setCity(CityTextF.getText());
            resume.setState(StateBox.getSelectedItem().toString());
            resume.setZipcode(Integer.parseInt(ZipTextF.getText()));
            resume.setMobile(Integer.parseInt(MobileTextF.getText()));
            resume.setEmail(EmailTextF.getText());
            
            resume.setDegree1(Degree1Box.getSelectedItem().toString());
            resume.setMajor1(Major1TextF.getText());
            resume.setCore1(Core1TextF.getText());
            if(BtnGroup_Status1.getSelection().equals(Graduate1RBtn.getModel()))
            {
                resume.setStatus1("Graduated");
            }else if (BtnGroup_Status1.getSelection().equals(InPro1RBtn.getModel()))
            {
                resume.setStatus1("In Progress");
            }
            
            resume.setDegree2(Degree2Box.getSelectedItem().toString());
            resume.setMajor2(Major2TextF.getText());
            resume.setCore2(Core2TextF.getText());
            if(BtnGroup_Status2.getSelection().equals(Graduate2RBtn.getModel()))
            {
                resume.setStatus2("Graduated");
            }else if (BtnGroup_Status2.getSelection().equals(InPro2RBtn.getModel()))
            {
                resume.setStatus2("In Progress");
            }
            
            resume.setJava(JavaCheck.isSelected());
            resume.setCplus(CplusCheck.isSelected());
            resume.setPhp(PhpCheck.isSelected());
            resume.setSql(SqlCheck.isSelected());
//            System.out.println(resume.isJava());
//            System.out.println(resume.isCplus());
//            System.out.println(resume.isPhp());
//            System.out.println(resume.isSql());
            
            resume.setLevel(LevelBox.getSelectedItem().toString());
            resume.setInstruction(InstructionTextF.getText());
            resume.setStatement(StatementTextArea.getText());
            
            JOptionPane.showMessageDialog(null,"Resume Created Successfully");
            
            FnameTextF.setText("");
            LnameTextF.setText("");
            AffilTextF.setText("");
            ImageJLable.setIcon(null);
            
            AddressTextF.setText("");
            AptTextF.setText("");
            CityTextF.setText("");
            ZipTextF.setText("");
            MobileTextF.setText("");
            EmailTextF.setText("");
            
            Major1TextF.setText("");
            Core1TextF.setText("");
            Major2TextF.setText("");
            Core2TextF.setText("");
            
            JavaCheck.setSelected(false);
            CplusCheck.setSelected(false);
            PhpCheck.setSelected(false);
            SqlCheck.setSelected(false);
            InstructionTextF.setText("");
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Resume Created Failed");
            rehis.deleteResume(resume);
//            System.out.println(resume.getFirstname());
        } 
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void UploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadBtnActionPerformed
        // TODO add your handling code here:

        Resume resume = new Resume();
        
        JFileChooser FChooser = new JFileChooser();
        int ReturnValue = FChooser.showOpenDialog(null);
        if(ReturnValue == JFileChooser.APPROVE_OPTION)
        {
            File selected = FChooser.getSelectedFile();
            resume.setImage(selected.getAbsolutePath());
            PathTextF.setText(resume.getImage());
//            System.out.println(resume.getImage());

            String path = resume.getImage();
            ImageIcon ThisImg = new ImageIcon(path);

            Image img1 = ThisImg.getImage().getScaledInstance(107, 107, WIDTH);
            ImageIcon img2 = new ImageIcon(img1);
            ImageJLable.setIcon(img2);

        }
    }//GEN-LAST:event_UploadBtnActionPerformed

    private void FemaleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRBtnActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextF;
    private javax.swing.JTextField AffilTextF;
    private javax.swing.JTextField AptTextF;
    private javax.swing.ButtonGroup BtnGroup_Gender;
    private javax.swing.ButtonGroup BtnGroup_Nation;
    private javax.swing.ButtonGroup BtnGroup_Status1;
    private javax.swing.ButtonGroup BtnGroup_Status2;
    private javax.swing.JRadioButton CitizenRBtn;
    private javax.swing.JTextField CityTextF;
    private javax.swing.JTextField Core1TextF;
    private javax.swing.JTextField Core2TextF;
    private javax.swing.JCheckBox CplusCheck;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JPanel CreateCoverPanel;
    private javax.swing.JComboBox<String> DateBox;
    private javax.swing.JComboBox<String> Degree1Box;
    private javax.swing.JComboBox<String> Degree2Box;
    private javax.swing.JTextField EmailTextF;
    private javax.swing.JRadioButton FemaleRBtn;
    private javax.swing.JTextField FnameTextF;
    private javax.swing.JRadioButton Graduate1RBtn;
    private javax.swing.JRadioButton Graduate2RBtn;
    private javax.swing.JLabel ImageJLable;
    private javax.swing.JRadioButton InPro1RBtn;
    private javax.swing.JRadioButton InPro2RBtn;
    private javax.swing.JTextField InstructionTextF;
    private javax.swing.JRadioButton InternationalRBtn;
    private javax.swing.JCheckBox JavaCheck;
    private javax.swing.JComboBox<String> LevelBox;
    private javax.swing.JTextField LnameTextF;
    private javax.swing.JTextField Major1TextF;
    private javax.swing.JTextField Major2TextF;
    private javax.swing.JRadioButton MaleRBtn;
    private javax.swing.JTextField MobileTextF;
    private javax.swing.JComboBox<String> MonthBox;
    private javax.swing.JTextField PathTextF;
    private javax.swing.JCheckBox PhpCheck;
    private javax.swing.JCheckBox SqlCheck;
    private javax.swing.JComboBox<String> StateBox;
    private javax.swing.JTextArea StatementTextArea;
    private javax.swing.JButton UploadBtn;
    private javax.swing.JComboBox<String> YearBox;
    private javax.swing.JTextField ZipTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
