/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Bussiness.Resume;
import Bussiness.ResumeHistory;
import java.awt.Color;
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VieJPanel
     */
    private ResumeHistory rehis;
    
    public ViewJPanel(ResumeHistory rehis) {
        initComponents();
        ImageJLable.setBorder(BorderFactory.createLineBorder(Color.black));
        
        this.rehis = rehis;
        
        displayJTable();
        
    }
    
    
    public void displayJTable()
    {   
        DefaultTableModel dtm = (DefaultTableModel)DisplayTable.getModel();
        dtm.setRowCount(0);
        
        for(Resume resume : rehis.getResumeHistory())
        {
            Object row[] = new Object[5];
            row[0] = resume;
            row[1] = resume.getLastname();
            row[2] = resume.getGender();
            row[3] = resume.getNation();
            row[4] = resume.getBirthday_year();
            dtm.addRow(row);
        }
        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ViewCoverPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DateTextF = new javax.swing.JTextField();
        YearTextF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EmailTextF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MobileTextF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AffilTextF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddressTextF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AptTextF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CityTextF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Major1TextF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ZipTextF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Core1TextF = new javax.swing.JTextField();
        Status1TextF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        InstructionTextF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatementTextArea = new javax.swing.JTextArea();
        GenderTextF = new javax.swing.JTextField();
        MonthTextF = new javax.swing.JTextField();
        StateTextF = new javax.swing.JTextField();
        Degree1TextF = new javax.swing.JTextField();
        LevelTextF = new javax.swing.JTextField();
        ImageJLable = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NationTextF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        DetailBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        Degree2TextF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Major2TextF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Status2TextF = new javax.swing.JTextField();
        Core2TextF = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        JavaCheck = new javax.swing.JCheckBox();
        CplusCheck = new javax.swing.JCheckBox();
        PhpCheck = new javax.swing.JCheckBox();
        SqlCheck = new javax.swing.JCheckBox();
        FnameTextF = new javax.swing.JTextField();
        LnameTextF = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setText("View  Resume");

        jLabel2.setText("FirstName:");

        jLabel3.setText("LastName:");

        jLabel4.setText("Gender:");

        jLabel5.setText("BirthDate:");

        DateTextF.setEnabled(false);

        YearTextF.setEnabled(false);

        jLabel6.setText("Year");

        jLabel7.setText("month");

        jLabel8.setText("date");

        jLabel9.setText("Mobile:");

        EmailTextF.setEnabled(false);

        jLabel10.setText("E-mail:");

        MobileTextF.setEnabled(false);

        jLabel11.setText("Affiliation:");

        AffilTextF.setEnabled(false);

        jLabel12.setText("Address:");

        AddressTextF.setEnabled(false);

        jLabel13.setText("Apt:");

        AptTextF.setEnabled(false);

        jLabel14.setText("City:");

        CityTextF.setEnabled(false);

        jLabel15.setText("State:");

        Major1TextF.setEnabled(false);

        jLabel16.setText("Zipcode:");

        ZipTextF.setEnabled(false);

        jLabel17.setText("Degree:");

        jLabel18.setText("Major:");

        jLabel19.setText("Core Course:");

        Core1TextF.setEnabled(false);

        Status1TextF.setEnabled(false);

        jLabel20.setText("Status:");

        jLabel21.setText("Skills:");

        InstructionTextF.setEnabled(false);

        jLabel22.setText("Level:");

        jLabel23.setText("Personal Statement:");

        StatementTextArea.setColumns(20);
        StatementTextArea.setRows(5);
        StatementTextArea.setEnabled(false);
        jScrollPane2.setViewportView(StatementTextArea);

        GenderTextF.setEnabled(false);

        MonthTextF.setEnabled(false);

        StateTextF.setEnabled(false);

        Degree1TextF.setEnabled(false);

        LevelTextF.setEnabled(false);

        ImageJLable.setBackground(new java.awt.Color(255, 255, 255));
        ImageJLable.setSize(new java.awt.Dimension(50, 50));

        jLabel24.setText("Nation:");

        NationTextF.setEnabled(false);

        jLabel27.setText("Instructions:");

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName", "Gender", "Nation", "Year of Birth"
            }
        ));
        jScrollPane3.setViewportView(DisplayTable);

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        DetailBtn.setText("View Details");
        DetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailBtnActionPerformed(evt);
            }
        });

        jLabel29.setText("Degree:");

        Degree2TextF.setEnabled(false);

        jLabel30.setText("Major:");

        Major2TextF.setEnabled(false);

        jLabel31.setText("Status:");

        Status2TextF.setEnabled(false);

        Core2TextF.setEnabled(false);

        jLabel32.setText("Core Course:");

        JavaCheck.setText("JAVA");
        JavaCheck.setEnabled(false);

        CplusCheck.setText("C++");
        CplusCheck.setEnabled(false);

        PhpCheck.setText("PHP");
        PhpCheck.setEnabled(false);

        SqlCheck.setText("SQL");
        SqlCheck.setEnabled(false);

        FnameTextF.setEnabled(false);

        LnameTextF.setEnabled(false);

        javax.swing.GroupLayout ViewCoverPanelLayout = new javax.swing.GroupLayout(ViewCoverPanel);
        ViewCoverPanel.setLayout(ViewCoverPanelLayout);
        ViewCoverPanelLayout.setHorizontalGroup(
            ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewCoverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewCoverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewCoverPanelLayout.createSequentialGroup()
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(DetailBtn)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Degree1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Major1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Degree2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Major2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Status2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Core2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Core1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InstructionTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(JavaCheck)
                                .addGap(18, 18, 18)
                                .addComponent(CplusCheck)
                                .addGap(18, 18, 18)
                                .addComponent(PhpCheck)
                                .addGap(18, 18, 18)
                                .addComponent(SqlCheck)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LevelTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane2))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FnameTextF)
                            .addComponent(GenderTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NationTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(LnameTextF)))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(MonthTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        ViewCoverPanelLayout.setVerticalGroup(
            ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteBtn)
                            .addComponent(DetailBtn))
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(FnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel24)
                            .addComponent(NationTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(MonthTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(DateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(StateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Degree1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(Major1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(Status1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Core1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Degree2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(Major2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(Status2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Core2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(JavaCheck)
                            .addComponent(CplusCheck)
                            .addComponent(PhpCheck)
                            .addComponent(SqlCheck)
                            .addComponent(jLabel22)
                            .addComponent(LevelTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(InstructionTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(ViewCoverPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = DisplayTable.getSelectedRow();
        
        if(selectedrow >= 0)
        {
            Resume resume = (Resume)DisplayTable.getValueAt(selectedrow, 0);
            
            FnameTextF.setText(resume.getFirstname());
            LnameTextF.setText(resume.getLastname());
            GenderTextF.setText(resume.getGender());
            NationTextF.setText(resume.getNation());
            MonthTextF.setText(resume.getBirthday_month());
            DateTextF.setText(resume.getBirthday_date());
            YearTextF.setText(resume.getBirthday_year());
            AffilTextF.setText(resume.getAffiliation());
            
            String path = resume.getImage();
            ImageIcon ThisImg = new ImageIcon(path);
//            ImageJLable.setIcon(ThisImg);            
            Image img1 = ThisImg.getImage().getScaledInstance(107, 107, WIDTH);
            ImageIcon img2 = new ImageIcon(img1);
            ImageJLable.setIcon(img2);


            AddressTextF.setText(resume.getAddress());
            AptTextF.setText(resume.getApt());
            CityTextF.setText(resume.getCity());
            StateTextF.setText(resume.getState());
            ZipTextF.setText(String.valueOf(resume.getZipcode()));
            MobileTextF.setText(String.valueOf(resume.getMobile()));
            EmailTextF.setText(resume.getEmail());
            
            Degree1TextF.setText(resume.getDegree1());
            Major1TextF.setText(resume.getMajor1());
            Status1TextF.setText(resume.getStatus1());
            Core1TextF.setText(resume.getCore1());
            Degree2TextF.setText(resume.getDegree2());
            Major2TextF.setText(resume.getMajor2());
            Status2TextF.setText(resume.getStatus2());
            Core2TextF.setText(resume.getCore2());
            
            JavaCheck.setSelected(resume.isJava());
            CplusCheck.setSelected(resume.isCplus());
            PhpCheck.setSelected(resume.isPhp());
            SqlCheck.setSelected(resume.isSql());
            LevelTextF.setText(resume.getLevel());
            InstructionTextF.setText(resume.getInstruction());
            StatementTextArea.setText(resume.getStatement());
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select a Item");
        }
        
    }//GEN-LAST:event_DetailBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = DisplayTable.getSelectedRow();
        
        if(selectedrow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you Like to delete it?" , "Warning" , dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION)
            {
                Resume resume = (Resume)DisplayTable.getValueAt(selectedrow, 0);
                rehis.deleteResume(resume);
                JOptionPane.showMessageDialog(null, "Vital Sign Deleted Successfully");
                displayJTable();
                
                FnameTextF.setText("");
                LnameTextF.setText("");
                GenderTextF.setText("");
                NationTextF.setText("");
                MonthTextF.setText("");
                DateTextF.setText("");
                YearTextF.setText("");
                AffilTextF.setText("");
                ImageJLable.setIcon(null);
            
                AddressTextF.setText("");
                AptTextF.setText("");
                CityTextF.setText("");
                StateTextF.setText("");
                ZipTextF.setText("");
                MobileTextF.setText("");
                EmailTextF.setText("");
            
                Degree1TextF.setText("");
                Major1TextF.setText("");
                Status1TextF.setText("");
                Core1TextF.setText("");
                Degree2TextF.setText("");
                Major2TextF.setText("");
                Status2TextF.setText("");
                Core2TextF.setText("");
            
                JavaCheck.setSelected(false);
                CplusCheck.setSelected(false);
                PhpCheck.setSelected(false);
                SqlCheck.setSelected(false);
                LevelTextF.setText("");
                InstructionTextF.setText("");
        }   
    }else{
            JOptionPane.showMessageDialog(null, "Please Select a Item");
         } 
        
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextF;
    private javax.swing.JTextField AffilTextF;
    private javax.swing.JTextField AptTextF;
    private javax.swing.JTextField CityTextF;
    private javax.swing.JTextField Core1TextF;
    private javax.swing.JTextField Core2TextF;
    private javax.swing.JCheckBox CplusCheck;
    private javax.swing.JTextField DateTextF;
    private javax.swing.JTextField Degree1TextF;
    private javax.swing.JTextField Degree2TextF;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DetailBtn;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JTextField EmailTextF;
    private javax.swing.JTextField FnameTextF;
    private javax.swing.JTextField GenderTextF;
    private javax.swing.JLabel ImageJLable;
    private javax.swing.JTextField InstructionTextF;
    private javax.swing.JCheckBox JavaCheck;
    private javax.swing.JTextField LevelTextF;
    private javax.swing.JTextField LnameTextF;
    private javax.swing.JTextField Major1TextF;
    private javax.swing.JTextField Major2TextF;
    private javax.swing.JTextField MobileTextF;
    private javax.swing.JTextField MonthTextF;
    private javax.swing.JTextField NationTextF;
    private javax.swing.JCheckBox PhpCheck;
    private javax.swing.JCheckBox SqlCheck;
    private javax.swing.JTextField StateTextF;
    private javax.swing.JTextArea StatementTextArea;
    private javax.swing.JTextField Status1TextF;
    private javax.swing.JTextField Status2TextF;
    private javax.swing.JPanel ViewCoverPanel;
    private javax.swing.JTextField YearTextF;
    private javax.swing.JTextField ZipTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
