/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Lab.VolunteerManager;

import Business.Enterprise.LabEnterprise;
import Business.UserAccount.UserAccount;
import Business.Volunteer.Volunteer;
import Business.WorkQueue.ResearchRequest;
import Business.WorkQueue.WorkRequest;
import Interface.Lab.Researcher.TestCreate;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class VolunteerManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerManagerWorkArea
     */
    JPanel processContainer;
    LabEnterprise enterprise;
    UserAccount useraccount;
    
    public VolunteerManagerWorkArea(JPanel processContainer, LabEnterprise enterprise, UserAccount useraccount) {
        initComponents();
        this.processContainer = processContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        
        jLabel3.setText(enterprise.getName());
        
        populateRequestjTable();
        populatevolunteersCatalogjTable();
        
    }
    public void populatevolunteersCatalogjTable(){
        DefaultTableModel model = (DefaultTableModel) volunteersCatalogjTable.getModel();
        model.setRowCount(0);
        
        for (Volunteer v : enterprise.getVolunteerCatalog().getVolunteerList()) {
            Object[] row = new Object[2];
            row[0] = v;
            row[1] = v.getStatus();
            model.addRow(row);
        }
    }
    
    
    
    public void populateRequestjTable(){
        DefaultTableModel model = (DefaultTableModel) testRequestjTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest workrequest : enterprise.getWorkQueue().getWorkRequestList()) {
            ResearchRequest s = (ResearchRequest) workrequest;
            
                Object[] row = new Object[5];
                row[0] = s;
                row[1] = s.getVolunteermanagerEmployee();
                row[2] = s.getStatus();
                row[3] = s.getVolunteersAmount();
                row[4] = s.getVolunteersList().getVolunteerList().size();
                model.addRow(row);
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        allocateVolunteerjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        volunteersCatalogjTable = new javax.swing.JTable();
        createVolunteerjButton = new javax.swing.JButton();
        receiveResearchjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        testRequestjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Volunteer Manager Work Area");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Work Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        allocateVolunteerjButton.setText("Allocate Volunteer");
        allocateVolunteerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateVolunteerjButtonActionPerformed(evt);
            }
        });

        volunteersCatalogjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volunteername", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(volunteersCatalogjTable);

        createVolunteerjButton.setText("Create volunteer");
        createVolunteerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVolunteerjButtonActionPerformed(evt);
            }
        });

        receiveResearchjButton.setText("Receive Research");
        receiveResearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveResearchjButtonActionPerformed(evt);
            }
        });

        testRequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "VolunteerResearcher", "Status", "Amount", "volunteer num"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(testRequestjTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(receiveResearchjButton)
                            .addGap(18, 18, 18)
                            .addComponent(allocateVolunteerjButton))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createVolunteerjButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveResearchjButton)
                    .addComponent(allocateVolunteerjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createVolunteerjButton)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Lab/VolunteerManager/volunteer.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receiveResearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveResearchjButtonActionPerformed
        // TODO add your handling code here:
       int selectedRow = testRequestjTable.getSelectedRow();

        if (selectedRow >= 0) {
            ResearchRequest request = (ResearchRequest) testRequestjTable.getValueAt(selectedRow, 0);
            if(request.getStatus() == WorkRequest.STATUS_3)  { 
                request.setVolunteermanagerEmployee(useraccount.getEmployee());
                request.setStatus(WorkRequest.STATUS_4);
                populateRequestjTable();
            }else{
                JOptionPane.showMessageDialog(null, "Plesae Select Proper Medicine Test");
            }
        }
    }//GEN-LAST:event_receiveResearchjButtonActionPerformed

    private void allocateVolunteerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateVolunteerjButtonActionPerformed
        // TODO add your handling code here:
        int requestselectedRow = testRequestjTable.getSelectedRow();
        int volunteerselectedRow = volunteersCatalogjTable.getSelectedRow();

        if (requestselectedRow >= 0 && volunteerselectedRow >= 0) {
            Volunteer v  =  (Volunteer) volunteersCatalogjTable.getValueAt(volunteerselectedRow, 0);
            if(v.getStatus().equals("Available")){
                ResearchRequest request = (ResearchRequest) testRequestjTable.getValueAt(requestselectedRow, 0);
                if(request.getStatus() == WorkRequest.STATUS_4){
                
                    request.getVolunteersList().addVolunteer(v);
                    v.setStatus("On Test");
                    JOptionPane.showMessageDialog(null, "Volunteer Inserted Successfully");
                    populateRequestjTable();
                    populatevolunteersCatalogjTable();
                
                    if(request.getVolunteersAmount() == request.getVolunteersList().getVolunteerList().size()){
                        request.setStatus(WorkRequest.STATUS_5);
                    
                        populateRequestjTable();
                        return;
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please Select the Right Test");
                }
            }else if(v.getStatus().equals("On Test")){
                JOptionPane.showMessageDialog(null, "Volunteer is On Test");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Plesae Select The Rows");
        }
    }//GEN-LAST:event_allocateVolunteerjButtonActionPerformed

    private void createVolunteerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVolunteerjButtonActionPerformed
        // TODO add your handling code here:
        CreateVolunteer createVolunteer = new CreateVolunteer(processContainer, enterprise);
        processContainer.add("CreateVolunteer", createVolunteer);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_createVolunteerjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allocateVolunteerjButton;
    private javax.swing.JButton createVolunteerjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton receiveResearchjButton;
    private javax.swing.JTable testRequestjTable;
    private javax.swing.JTable volunteersCatalogjTable;
    // End of variables declaration//GEN-END:variables
}
