/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customerInterface;

import Bussiness.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Eric
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel processJPanel;
    private ProductDirectory productDirectory;
    
    public CustomerAreaJPanel(JPanel processJPanel, ProductDirectory productDirectory) {
        initComponents();
        this.processJPanel = processJPanel;
        this.productDirectory = productDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComputerCatalogBtn = new javax.swing.JButton();
        PrinterCatalogBtn = new javax.swing.JButton();
        HardwareCatalogBtn = new javax.swing.JButton();
        SoftwareCatalogBtn = new javax.swing.JButton();

        ComputerCatalogBtn.setText("View Computer Catalog");
        ComputerCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerCatalogBtnActionPerformed(evt);
            }
        });

        PrinterCatalogBtn.setText("View Printer Catalog");
        PrinterCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrinterCatalogBtnActionPerformed(evt);
            }
        });

        HardwareCatalogBtn.setText("View Hardware Catalog");
        HardwareCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardwareCatalogBtnActionPerformed(evt);
            }
        });

        SoftwareCatalogBtn.setText("View Software Catalog");
        SoftwareCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoftwareCatalogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoftwareCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HardwareCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrinterCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComputerCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ComputerCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrinterCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HardwareCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SoftwareCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComputerCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputerCatalogBtnActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewjp = new ViewJPanel(processJPanel , productDirectory.computerList() , productDirectory);
        processJPanel.add("ViewJPanel", viewjp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_ComputerCatalogBtnActionPerformed

    private void PrinterCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrinterCatalogBtnActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewjp = new ViewJPanel(processJPanel , productDirectory.printerList() , productDirectory);
        processJPanel.add("ViewJPanel", viewjp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_PrinterCatalogBtnActionPerformed

    private void HardwareCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardwareCatalogBtnActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewjp = new ViewJPanel(processJPanel , productDirectory.hardwareList() , productDirectory);
        processJPanel.add("ViewJPanel", viewjp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_HardwareCatalogBtnActionPerformed

    private void SoftwareCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoftwareCatalogBtnActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewjp = new ViewJPanel(processJPanel , productDirectory.softwareList() , productDirectory);
        processJPanel.add("ViewJPanel", viewjp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_SoftwareCatalogBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComputerCatalogBtn;
    private javax.swing.JButton HardwareCatalogBtn;
    private javax.swing.JButton PrinterCatalogBtn;
    private javax.swing.JButton SoftwareCatalogBtn;
    // End of variables declaration//GEN-END:variables
}
