/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customerInterface;

import Bussiness.Product;
import Bussiness.ProductDirectory;
import Bussiness.SortByPrice;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel processJPanel;
    private ArrayList<Product> InputList;
    private ProductDirectory productDirectory;
    
    public ViewJPanel(JPanel processJPanel, ArrayList<Product> InputList , ProductDirectory productDirectory) {
        initComponents();
        this.processJPanel = processJPanel;
        this.InputList = InputList;
        this.productDirectory = productDirectory;
        
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) DisplayJtb.getModel();
        dtm.setRowCount(0);
        
        for(Product product : InputList){
            Object[] row = new Object[6];
            row[0] = product;
            row[1] = product.getType();
            row[2] = product.getModelNumber();
            row[3] = product.getDescription();
            row[4] = product.getVendor();
            row[5] = product.getFloorPrice();
            
            dtm.addRow(row);
        }
//        productDirectory.setVirtualList(InputList);
    }
    
    public void populateTable(ArrayList<Product> sortedList){
        DefaultTableModel dtm = (DefaultTableModel) DisplayJtb.getModel();
        dtm.setRowCount(0);
        
        for(Product product : sortedList){
            Object[] row = new Object[6];
            row[0] = product;
            row[1] = product.getType();
            row[2] = product.getModelNumber();
            row[3] = product.getDescription();
            row[4] = product.getVendor();
            row[5] = product.getFloorPrice();
            
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayJtb = new javax.swing.JTable();
        ApplyBtn = new javax.swing.JButton();
        DetailBtn = new javax.swing.JButton();
        SortBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        SearchBox = new javax.swing.JComboBox<>();
        SearchTextF = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        jLabel1.setText("Product Catalog");

        DisplayJtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Model Number", "Description", "Vendor", "Floor Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(DisplayJtb);
        if (DisplayJtb.getColumnModel().getColumnCount() > 0) {
            DisplayJtb.getColumnModel().getColumn(0).setResizable(false);
            DisplayJtb.getColumnModel().getColumn(1).setResizable(false);
            DisplayJtb.getColumnModel().getColumn(2).setResizable(false);
            DisplayJtb.getColumnModel().getColumn(3).setResizable(false);
            DisplayJtb.getColumnModel().getColumn(4).setResizable(false);
            DisplayJtb.getColumnModel().getColumn(5).setResizable(false);
        }

        ApplyBtn.setText("Apply");
        ApplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyBtnActionPerformed(evt);
            }
        });

        DetailBtn.setText("View Details");
        DetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailBtnActionPerformed(evt);
            }
        });

        SortBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By Time", "Sort By Floor Price" }));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Search By :");

        SearchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All products", "Name", "Vendor", "Description", "All Itmes Above" }));

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("<Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(SortBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ApplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DetailBtn))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DetailBtn)
                    .addComponent(SortBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApplyBtn))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn))
                .addGap(82, 82, 82))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        processJPanel.remove(this);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.previous(processJPanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void DetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = DisplayJtb.getSelectedRow();
        if(selectedRow >= 0){
            Product product = (Product)DisplayJtb.getValueAt(selectedRow, 0);
            DetailJPanel detailjp = new DetailJPanel(processJPanel , product);
            processJPanel.add("DetailJPanel" , detailjp);
            CardLayout layout = (CardLayout)processJPanel.getLayout();
            layout.next(processJPanel);  
        }else{
            JOptionPane.showMessageDialog(null, "Please Select a Row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DetailBtnActionPerformed

    private void ApplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyBtnActionPerformed
        // TODO add your handling code here:
        if(SortBox.getSelectedItem().equals("Sort By Time")){
            ArrayList<Product> sortedList = new ArrayList<>();
            for(Product product : productDirectory.getVirtualList()){
                sortedList.add(product);
            }
            populateTable(sortedList);
        }else if(SortBox.getSelectedItem().equals("Sort By Floor Price")){
            ArrayList<Product> sortedList = new ArrayList<>();
            for(Product product : productDirectory.getVirtualList()){
                sortedList.add(product);
            }
            Collections.sort(sortedList, new SortByPrice());
            populateTable(sortedList);
        }
    }//GEN-LAST:event_ApplyBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
//        try{
            if(SearchBox.getSelectedItem().equals("All products")){
                populateTable();
            }else if(SearchBox.getSelectedItem().equals("Name")){
                ArrayList<Product> resultList = productDirectory.searchByName(SearchTextF.getText());
                if(resultList.size() == 0){
                    JOptionPane.showMessageDialog(null, "Product Name Doesn't Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                     populateTable(resultList);
                     productDirectory.setVirtualList(resultList);
                }
            }else if(SearchBox.getSelectedItem().equals("Vendor")){
                ArrayList<Product> resultList = productDirectory.searchByVendor(SearchTextF.getText());
                if(resultList.size() == 0){
                    JOptionPane.showMessageDialog(null, "Product Vendor Doesn't Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    populateTable(resultList);
                    productDirectory.setVirtualList(resultList);
                }
            }else if(SearchBox.getSelectedItem().equals("Description")){
                ArrayList<Product> resultList = productDirectory.searchByDescription(SearchTextF.getText());
                if(resultList.size() == 0){
                    JOptionPane.showMessageDialog(null, "Product Description Doesn't Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    populateTable(resultList);
                    productDirectory.setVirtualList(resultList);
                }
            }else if(SearchBox.getSelectedItem().equals("All Itmes Above")){
                ArrayList<Product> resultList = productDirectory.searchByAll(SearchTextF.getText());
                if(resultList == null){
                    JOptionPane.showMessageDialog(null, "Product Doesn't Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    populateTable(resultList);
                    productDirectory.setVirtualList(resultList);
                }
            }
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null, "Error", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DetailBtn;
    private javax.swing.JTable DisplayJtb;
    private javax.swing.JComboBox<String> SearchBox;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTextF;
    private javax.swing.JComboBox<String> SortBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
