/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Lab.Assistant;

import Business.Enterprise.LabEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ResearchRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class AssistantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AssistantWorkArea
     */
    
 JPanel userProcessContainer;
 LabEnterprise enterprise;
 UserAccount userAccount;   
    
    public AssistantWorkArea(JPanel userProcessContainer, LabEnterprise enterprise, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        AssistantLabel.setText(userAccount.getEmployee().getName());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) testRequestjTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest workrequest : enterprise.getWorkQueue().getWorkRequestList()) {
            ResearchRequest s = (ResearchRequest) workrequest;


                Object[] row = new Object[4];
                row[0] = s;
                row[1] = s.getAssistantEmployee();
                row[2] = s.getVolunteermanagerEmployee();
                row[3] = s.getStatus();
                model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        volunteersAmountjTextField = new javax.swing.JTextField();
        AssistantLabel = new javax.swing.JLabel();
        AcceptTestjButton = new javax.swing.JButton();
        TestFinishjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cycleTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testRequestjTable = new javax.swing.JTable();
        budgetTextField = new javax.swing.JTextField();
        ResultCo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Assistant Work Area");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Work Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        AssistantLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AssistantLabel.setText("Label");

        AcceptTestjButton.setText("Accept Test");
        AcceptTestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptTestjButtonActionPerformed(evt);
            }
        });

        TestFinishjButton.setText("Test Finish");
        TestFinishjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestFinishjButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Budget:");

        jLabel5.setText("Cycle:");

        jLabel6.setText("Volunteer Amount:");

        cycleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cycleTextFieldActionPerformed(evt);
            }
        });

        testRequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Assistant", "VolunteerResearcher", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(testRequestjTable);

        ResultCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Successfull", "Failure" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AcceptTestjButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TestFinishjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResultCo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volunteersAmountjTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(budgetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cycleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssistantLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(budgetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cycleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(volunteersAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ResultCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TestFinishjButton)))
                .addGap(18, 18, 18)
                .addComponent(AcceptTestjButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Lab/Assistant/work.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(831, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptTestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptTestjButtonActionPerformed
        // TODO add your handling code here:
//        判定是否已经有assis
        if(budgetTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Plesae Enter Budget");
            return;
        }
        if(cycleTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Plesae Enter Cycle");
            return;
        }
        if(volunteersAmountjTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Plesae Enter Volunteer Amount");
            return;
        }
        
        int selectedRow=testRequestjTable.getSelectedRow();
            if (selectedRow >= 0) {
                ResearchRequest research = (ResearchRequest) testRequestjTable.getValueAt(selectedRow, 0);
                if(research.getStatus() == WorkRequest.STATUS_1){
                    research.setStatus(WorkRequest.STATUS_2);
                    research.setAssistantEmployee(userAccount.getEmployee());
                    research.setVolunteersAmount(Integer.parseInt(volunteersAmountjTextField.getText()));
                    research.setBudget(Integer.parseInt(budgetTextField.getText()));
                    research.setResearchCycle(cycleTextField.getText());
                    JOptionPane.showMessageDialog(null, "Medicine Test Is assigned by You");
                    budgetTextField.setText("");
                    cycleTextField.setText("");
                    volunteersAmountjTextField.setText("");
                    populateTable();
                }
        }    
    }//GEN-LAST:event_AcceptTestjButtonActionPerformed

    private void TestFinishjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestFinishjButtonActionPerformed
        // TODO add your handling code here:
        //判定status = testing
        int selectedRow=testRequestjTable.getSelectedRow();
            if (selectedRow >= 0) {
            ResearchRequest research = (ResearchRequest) testRequestjTable.getValueAt(selectedRow, 0);
                if(research.getStatus() == WorkRequest.STATUS_5){
                    research.setStatus(WorkRequest.STATUS_6);
                    
                    if(ResultCo.getSelectedItem().equals("Successfull")){
                        research.setResult("Successfull");
                    }else if(ResultCo.getSelectedItem().equals("Failure")){
                        research.setResult("Failure");
                    }
                    
                    JOptionPane.showMessageDialog(null, "Medicine Test Complete");
                    populateTable();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please Select a Row");
            }
    }//GEN-LAST:event_TestFinishjButtonActionPerformed

    private void cycleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cycleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cycleTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptTestjButton;
    private javax.swing.JLabel AssistantLabel;
    private javax.swing.JComboBox<String> ResultCo;
    private javax.swing.JButton TestFinishjButton;
    private javax.swing.JTextField budgetTextField;
    private javax.swing.JTextField cycleTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable testRequestjTable;
    private javax.swing.JTextField volunteersAmountjTextField;
    // End of variables declaration//GEN-END:variables
}
