/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Company.Manager;

import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LabEnterprise;
import Business.Network.Network;
import Business.WorkQueue.MedicineTrade;
import Business.WorkQueue.ResearchRequest;
import Business.WorkQueue.WorkRequest;
import Interface.Hospital.Buyer.BuyerWorkArea;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class ManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkArea
     */
    
    JPanel processContainer;
    CompanyEnterprise enterprise;
    Network network;
    
    public ManagerWorkArea(JPanel processContainer, CompanyEnterprise enterprise, Network network) {
        initComponents();
        
        this.processContainer = processContainer;
        this.enterprise = enterprise;
        this.network = network;
        
        populateCombo();
        populateMedicineTable();
    }
    
    private void populateCombo(){
        LabComboBox.removeAllItems();
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.ResearchLab.getValue())){
                LabComboBox.addItem(enterprise);
            }
        }
        populateTestTable();
    }
    
    public void populateTestTable() {
        
        DefaultTableModel model = (DefaultTableModel) MedicineTable.getModel();
        model.setRowCount(0);
        
        LabEnterprise labEnterprise = (LabEnterprise)LabComboBox.getSelectedItem();
        
        for (WorkRequest request : labEnterprise.getWorkQueue().getWorkRequestList()) {
            
            ResearchRequest req = (ResearchRequest)request;
            
            Object[] row = new Object[5];
            row[0] = req;
            row[1] = req.getStatus();
            row[2] = req.getMedicine().getFunction();
            row[3] = req.getBudget();
            row[4] = req.getResult();
            model.addRow(row);
        }
    }
    
    public void populateProperTestTable() {
        
        DefaultTableModel model = (DefaultTableModel) MedicineTable.getModel();
        model.setRowCount(0);
        
        LabEnterprise labEnterprise = (LabEnterprise)LabComboBox.getSelectedItem();
        
        for (WorkRequest request : labEnterprise.getWorkQueue().getWorkRequestList()) {
            
            ResearchRequest req = (ResearchRequest)request;
            if(req.getStatus().equals(WorkRequest.STATUS_2)){
                Object[] row = new Object[5];
                row[0] = req;
                row[1] = req.getStatus();
                row[2] = req.getMedicine().getFunction();
                row[3] = req.getBudget();
                row[4] = req.getResult();
                model.addRow(row);
            }
        }
    }
    
    public void populateMedicineTable() {
        
        DefaultTableModel model = (DefaultTableModel) SponsorMedicineTable.getModel();
        model.setRowCount(0);
        
        for(Enterprise enterprise_1 : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise_1.getEnterpriseType().equals(Enterprise.EnterpriseType.ResearchLab)){
                LabEnterprise labE = (LabEnterprise)enterprise_1;
                for(WorkRequest workR : labE.getWorkQueue().getWorkRequestList()){
                    
                    if(workR.getStatus().equals(WorkRequest.STATUS_1) || workR.getStatus().equals(WorkRequest.STATUS_2)){
                        break;
                    }else{
                        ResearchRequest rer = (ResearchRequest)workR;
                        if(rer.getSponsor().equals(enterprise.getName())){
                            Object[] row = new Object[6];
                            row[0] = rer;
                            row[1] = rer.getStatus();
                            row[2] = rer.getMedicine().getFunction();
                            row[3] = rer.getMoneyReceive();
                            row[4] = rer.getLabName();
                            row[5] = rer.getResult();
                            model.addRow(row);
                        }
                    }
                    
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineTable = new javax.swing.JTable();
        CostSpinner = new javax.swing.JSpinner();
        ProcessBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SetComboBox = new javax.swing.JComboBox<>();
        LabComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SponsorMedicineTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setText("Company Manager WorkArea");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lab and Medicine Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Research Medicine Catalog :");

        MedicineTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine_Name", "Status", "Applicability", "Budge", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MedicineTable);

        CostSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ProcessBtn.setText("Be a Sponsor");
        ProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Budget :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Research Lab :");

        SetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Get all Medicine Test", "Get Proper Medicine Test" }));
        SetComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetComboBoxActionPerformed(evt);
            }
        });

        LabComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CostSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProcessBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CostSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcessBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Sponsored Catalog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        SponsorMedicineTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SponsorMedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine_Name", "Status", "Applicability", "Cost", "Lab Name", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SponsorMedicineTable);
        if (SponsorMedicineTable.getColumnModel().getColumnCount() > 0) {
            SponsorMedicineTable.getColumnModel().getColumn(0).setResizable(false);
            SponsorMedicineTable.getColumnModel().getColumn(1).setResizable(false);
            SponsorMedicineTable.getColumnModel().getColumn(2).setResizable(false);
            SponsorMedicineTable.getColumnModel().getColumn(3).setResizable(false);
            SponsorMedicineTable.getColumnModel().getColumn(4).setResizable(false);
            SponsorMedicineTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Company/Manager/money.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LabComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabComboBoxActionPerformed
        // TODO add your handling code here:
        populateTestTable();
    }//GEN-LAST:event_LabComboBoxActionPerformed

    private void ProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = MedicineTable.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }
        
        LabEnterprise labEnterprise = (LabEnterprise)LabComboBox.getSelectedItem();
        String labName = labEnterprise.getName();

        ResearchRequest researchRequest = (ResearchRequest)MedicineTable.getValueAt(selectedRow, 0);
        int cost = (Integer)CostSpinner.getValue();

        if(cost <= researchRequest.getBudget()){
            JOptionPane.showMessageDialog(null, "Cost cannot be less than Budget");
            return;
        }

        if(researchRequest.getStatus().equals(WorkRequest.STATUS_2)){
            
            researchRequest.setMoneyReceive(cost);
            researchRequest.setStatus(WorkRequest.STATUS_3);
            researchRequest.setSponsor(enterprise.getName());
            researchRequest.setLabName(labName);
            
            populateTestTable();
            populateMedicineTable();
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Select the Medicine with Proper Ststus");
        }
    }//GEN-LAST:event_ProcessBtnActionPerformed

    private void SetComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetComboBoxActionPerformed
        // TODO add your handling code here:
        if(SetComboBox.getSelectedItem().equals("Get all Medicine Test")){
            populateTestTable();
        }else if(SetComboBox.getSelectedItem().equals("Get Proper Medicine Test")){
            populateProperTestTable();
        }
    }//GEN-LAST:event_SetComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CostSpinner;
    private javax.swing.JComboBox LabComboBox;
    private javax.swing.JTable MedicineTable;
    private javax.swing.JButton ProcessBtn;
    private javax.swing.JComboBox<String> SetComboBox;
    private javax.swing.JTable SponsorMedicineTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
