/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Initialization;

import Business.College;
import Business.CollegeCatalog;
import Business.Course;
import Business.CourseOffering;
import Business.Degree;
import Business.DegreeCatalog;
import Business.Department;
import Business.DepartmentCatalog;
import Business.DepartmentCourseSchedule;
import Business.Student;
import Business.StudentDirectory;
import Business.University;
import Business.UniversityCatalog;
import java.util.ArrayList;

/**
 *
 * @author Eric
 */
public class Initialization {
    
    public static UniversityCatalog Initialization() {
        
        UniversityCatalog universityCatalog = new UniversityCatalog();
        
        University university_1 = universityCatalog.addUniversity();
        University university_2 = universityCatalog.addUniversity();
        
        university_1.setUniversityID("1");
        university_1.setUniversityName("NEU");
        university_2.setUniversityID("2");
        university_2.setUniversityName("BU ");
    
        CollegeCatalog collegeCatalog_1 = university_1.getCollegeCatalog();
        CollegeCatalog collegeCatalog_2 = university_2.getCollegeCatalog();
        
//        collegeCatalog_1.setUniversityName("NEU");
//        collegeCatalog_2.setUniversityName("BU ");
        
        Initialization.Initialization_Student();
    
        College college_1_1 = collegeCatalog_1.addCollege();
        College college_1_2 = collegeCatalog_1.addCollege();
        College college_2_1 = collegeCatalog_2.addCollege();
        College college_2_2 = collegeCatalog_2.addCollege();
        
        college_1_1.setCollegeID("1");
        college_1_1.setCollegeName("COE");
        college_1_2.setCollegeID("2");
        college_1_2.setCollegeName("COS");
        college_2_1.setCollegeID("3");
        college_2_1.setCollegeName("COE");
        college_2_2.setCollegeID("4");
        college_2_2.setCollegeName("COS");
        
        DepartmentCatalog departmentCatalog_1_1 = college_1_1.getDepartmentcatalog();
        DepartmentCatalog departmentCatalog_1_2 = college_1_2.getDepartmentcatalog();
        DepartmentCatalog departmentCatalog_2_1 = college_2_1.getDepartmentcatalog();
        DepartmentCatalog departmentCatalog_2_2 = college_2_2.getDepartmentcatalog();
        
        Department department_1 = departmentCatalog_1_1.addDepartment();
        Department department_2 = departmentCatalog_1_1.addDepartment();
        Department department_3 = departmentCatalog_1_2.addDepartment();
        Department department_4 = departmentCatalog_1_2.addDepartment();
        Department department_5 = departmentCatalog_2_1.addDepartment();
        Department department_6 = departmentCatalog_2_1.addDepartment();
        Department department_7 = departmentCatalog_2_2.addDepartment();
        Department department_8 = departmentCatalog_2_2.addDepartment();
        
        department_1.setDepartmentID("1");
        department_1.setDepartmentName("IS");
        department_2.setDepartmentID("2");
        department_2.setDepartmentName("CS");
        department_3.setDepartmentID("3");
        department_3.setDepartmentName("Math");
        department_4.setDepartmentID("4");
        department_4.setDepartmentName("Phys");
        department_5.setDepartmentID("5");
        department_5.setDepartmentName("IS");
        department_6.setDepartmentID("6");
        department_6.setDepartmentName("CS");
        department_7.setDepartmentID("7");
        department_7.setDepartmentName("Math");
        department_8.setDepartmentID("8");
        department_8.setDepartmentName("Phys");
        
        DepartmentCourseSchedule departmentCourseSchedule_1_1 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_1_2 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_1_3 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_1_4 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_1_5 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_1_6 = department_1.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_1 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_2 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_3 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_4 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_5 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_2_6 = department_2.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_1 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_2 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_3 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_4 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_5 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_3_6 = department_3.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_1 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_2 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_3 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_4 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_5 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_4_6 = department_4.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_1 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_2 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_3 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_4 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_5 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_5_6 = department_5.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_1 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_2 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_3 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_4 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_5 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_6_6 = department_6.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_1 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_2 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_3 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_4 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_5 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_7_6 = department_7.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_1 = department_8.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_2 = department_8.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_3 = department_8.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_4 = department_8.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_5 = department_8.getDepartmentCourseList();
        DepartmentCourseSchedule departmentCourseSchedule_8_6 = department_8.getDepartmentCourseList();
        
        departmentCourseSchedule_1_1.setScheduleID("1 ");
        departmentCourseSchedule_1_2.setScheduleID("2 ");
        departmentCourseSchedule_1_3.setScheduleID("3 ");
        departmentCourseSchedule_1_4.setScheduleID("4 ");
        departmentCourseSchedule_1_5.setScheduleID("5 ");
        departmentCourseSchedule_1_6.setScheduleID("6 ");
        departmentCourseSchedule_2_1.setScheduleID("7 ");
        departmentCourseSchedule_2_2.setScheduleID("8 ");
        departmentCourseSchedule_2_3.setScheduleID("9 ");
        departmentCourseSchedule_2_4.setScheduleID("10");
        departmentCourseSchedule_2_5.setScheduleID("11");
        departmentCourseSchedule_2_6.setScheduleID("12");
        departmentCourseSchedule_3_1.setScheduleID("13");
        departmentCourseSchedule_3_2.setScheduleID("14");
        departmentCourseSchedule_3_3.setScheduleID("15");
        departmentCourseSchedule_3_4.setScheduleID("16");
        departmentCourseSchedule_3_5.setScheduleID("17");
        departmentCourseSchedule_3_6.setScheduleID("18");
        departmentCourseSchedule_4_1.setScheduleID("19");
        departmentCourseSchedule_4_2.setScheduleID("20");
        departmentCourseSchedule_4_3.setScheduleID("21");
        departmentCourseSchedule_4_4.setScheduleID("22");
        departmentCourseSchedule_4_5.setScheduleID("23");
        departmentCourseSchedule_4_6.setScheduleID("24");
        departmentCourseSchedule_5_1.setScheduleID("25");
        departmentCourseSchedule_5_2.setScheduleID("26");
        departmentCourseSchedule_5_3.setScheduleID("27");
        departmentCourseSchedule_5_4.setScheduleID("28");
        departmentCourseSchedule_5_5.setScheduleID("29");
        departmentCourseSchedule_5_6.setScheduleID("30");
        departmentCourseSchedule_6_1.setScheduleID("31");
        departmentCourseSchedule_6_2.setScheduleID("32");
        departmentCourseSchedule_6_3.setScheduleID("33");
        departmentCourseSchedule_6_4.setScheduleID("34");
        departmentCourseSchedule_6_5.setScheduleID("35");
        departmentCourseSchedule_6_6.setScheduleID("36");
        departmentCourseSchedule_7_1.setScheduleID("37");
        departmentCourseSchedule_7_2.setScheduleID("38");
        departmentCourseSchedule_7_3.setScheduleID("39");
        departmentCourseSchedule_7_4.setScheduleID("40");
        departmentCourseSchedule_7_5.setScheduleID("41");
        departmentCourseSchedule_7_6.setScheduleID("42");
        departmentCourseSchedule_8_1.setScheduleID("43");
        departmentCourseSchedule_8_2.setScheduleID("44");
        departmentCourseSchedule_8_3.setScheduleID("45");
        departmentCourseSchedule_8_4.setScheduleID("46");
        departmentCourseSchedule_8_5.setScheduleID("47");
        departmentCourseSchedule_8_6.setScheduleID("48");
        
        CourseOffering courseOffering1 = departmentCourseSchedule_1_1.addCourseOffering();
        CourseOffering courseOffering2 = departmentCourseSchedule_1_2.addCourseOffering();
        CourseOffering courseOffering3 = departmentCourseSchedule_1_3.addCourseOffering();
        CourseOffering courseOffering4 = departmentCourseSchedule_1_4.addCourseOffering();
        CourseOffering courseOffering5 = departmentCourseSchedule_1_5.addCourseOffering();
        CourseOffering courseOffering6 = departmentCourseSchedule_1_6.addCourseOffering();
        CourseOffering courseOffering7 = departmentCourseSchedule_2_1.addCourseOffering();
        CourseOffering courseOffering8 = departmentCourseSchedule_2_2.addCourseOffering();
        CourseOffering courseOffering9 = departmentCourseSchedule_2_3.addCourseOffering();
        CourseOffering courseOffering10 = departmentCourseSchedule_2_4.addCourseOffering();
        CourseOffering courseOffering11 = departmentCourseSchedule_2_5.addCourseOffering();
        CourseOffering courseOffering12 = departmentCourseSchedule_2_6.addCourseOffering();
        CourseOffering courseOffering13 = departmentCourseSchedule_3_1.addCourseOffering();
        CourseOffering courseOffering14 = departmentCourseSchedule_3_2.addCourseOffering();
        CourseOffering courseOffering15 = departmentCourseSchedule_3_3.addCourseOffering();
        CourseOffering courseOffering16 = departmentCourseSchedule_3_4.addCourseOffering();
        CourseOffering courseOffering17 = departmentCourseSchedule_3_5.addCourseOffering();
        CourseOffering courseOffering18 = departmentCourseSchedule_3_6.addCourseOffering();
        CourseOffering courseOffering19 = departmentCourseSchedule_4_1.addCourseOffering();
        CourseOffering courseOffering20 = departmentCourseSchedule_4_2.addCourseOffering();
        CourseOffering courseOffering21 = departmentCourseSchedule_4_3.addCourseOffering();
        CourseOffering courseOffering22 = departmentCourseSchedule_4_4.addCourseOffering();
        CourseOffering courseOffering23 = departmentCourseSchedule_4_5.addCourseOffering();
        CourseOffering courseOffering24 = departmentCourseSchedule_4_6.addCourseOffering();
        CourseOffering courseOffering25 = departmentCourseSchedule_5_1.addCourseOffering();
        CourseOffering courseOffering26 = departmentCourseSchedule_5_2.addCourseOffering();
        CourseOffering courseOffering27 = departmentCourseSchedule_5_3.addCourseOffering();
        CourseOffering courseOffering28 = departmentCourseSchedule_5_4.addCourseOffering();
        CourseOffering courseOffering29 = departmentCourseSchedule_5_5.addCourseOffering();
        CourseOffering courseOffering30 = departmentCourseSchedule_5_6.addCourseOffering();
        CourseOffering courseOffering31 = departmentCourseSchedule_6_1.addCourseOffering();
        CourseOffering courseOffering32 = departmentCourseSchedule_6_2.addCourseOffering();
        CourseOffering courseOffering33 = departmentCourseSchedule_6_3.addCourseOffering();
        CourseOffering courseOffering34 = departmentCourseSchedule_6_4.addCourseOffering();
        CourseOffering courseOffering35 = departmentCourseSchedule_6_5.addCourseOffering();
        CourseOffering courseOffering36 = departmentCourseSchedule_6_6.addCourseOffering();
        CourseOffering courseOffering37 = departmentCourseSchedule_7_1.addCourseOffering();
        CourseOffering courseOffering38 = departmentCourseSchedule_7_2.addCourseOffering();
        CourseOffering courseOffering39 = departmentCourseSchedule_7_3.addCourseOffering();
        CourseOffering courseOffering40 = departmentCourseSchedule_7_4.addCourseOffering();
        CourseOffering courseOffering41 = departmentCourseSchedule_7_5.addCourseOffering();
        CourseOffering courseOffering42 = departmentCourseSchedule_7_6.addCourseOffering();
        CourseOffering courseOffering43 = departmentCourseSchedule_8_1.addCourseOffering();
        CourseOffering courseOffering44 = departmentCourseSchedule_8_2.addCourseOffering();
        CourseOffering courseOffering45 = departmentCourseSchedule_8_3.addCourseOffering();
        CourseOffering courseOffering46 = departmentCourseSchedule_8_4.addCourseOffering();
        CourseOffering courseOffering47 = departmentCourseSchedule_8_5.addCourseOffering();
        CourseOffering courseOffering48 = departmentCourseSchedule_8_6.addCourseOffering();
        
        courseOffering1.setCourseOfferingID("1 ");
        courseOffering1.setBuilding("1");
        courseOffering1.setRoom("1 ");
        courseOffering1.setTeacherID("1 ");
        courseOffering1.setYear("2016");
        courseOffering1.setSeason("Fall");
        courseOffering1.setCourseName("AED       ");
        courseOffering2.setCourseOfferingID("2 ");
        courseOffering2.setBuilding("1");
        courseOffering2.setRoom("2 ");
        courseOffering2.setTeacherID("2 ");
        courseOffering2.setYear("2016");
        courseOffering2.setSeason("Fall");
        courseOffering2.setCourseName("DB        ");
        courseOffering3.setCourseOfferingID("3 ");
        courseOffering3.setBuilding("1");
        courseOffering3.setRoom("3 ");
        courseOffering3.setTeacherID("3 ");
        courseOffering3.setYear("2016");
        courseOffering3.setSeason("Fall");
        courseOffering3.setCourseName("WEB       ");
        courseOffering4.setCourseOfferingID("4 ");
        courseOffering4.setBuilding("1");
        courseOffering4.setRoom("4 ");
        courseOffering4.setTeacherID("4 ");
        courseOffering4.setYear("2016");
        courseOffering4.setSeason("Fall");
        courseOffering4.setCourseName("AED       ");
        courseOffering5.setCourseOfferingID("5 ");
        courseOffering5.setBuilding("1");
        courseOffering5.setRoom("5 ");
        courseOffering5.setTeacherID("5 ");
        courseOffering5.setYear("2016");
        courseOffering5.setSeason("Fall");
        courseOffering5.setCourseName("DB        ");
        courseOffering6.setCourseOfferingID("6 ");
        courseOffering6.setBuilding("1");
        courseOffering6.setRoom("6 ");
        courseOffering6.setTeacherID("6 ");
        courseOffering6.setYear("2016");
        courseOffering6.setSeason("Fall");
        courseOffering6.setCourseName("WEB       ");
        courseOffering7.setCourseOfferingID("7 ");
        courseOffering7.setBuilding("1");
        courseOffering7.setRoom("7 ");
        courseOffering7.setTeacherID("7 ");
        courseOffering7.setYear("2016");
        courseOffering7.setSeason("Fall");
        courseOffering7.setCourseName("Java      ");
        courseOffering8.setCourseOfferingID("8 ");
        courseOffering8.setBuilding("1");
        courseOffering8.setRoom("8 ");
        courseOffering8.setTeacherID("8 ");
        courseOffering8.setYear("2016");
        courseOffering8.setSeason("Fall");
        courseOffering8.setCourseName("C#        ");
        courseOffering9.setCourseOfferingID("9 ");
        courseOffering9.setBuilding("1");
        courseOffering9.setRoom("9 ");
        courseOffering9.setTeacherID("9 ");
        courseOffering9.setYear("2016");
        courseOffering9.setSeason("Fall");
        courseOffering9.setCourseName("C++       ");
        courseOffering10.setCourseOfferingID("10");
        courseOffering10.setBuilding("1");
        courseOffering10.setRoom("10");
        courseOffering10.setTeacherID("10");
        courseOffering10.setYear("2016");
        courseOffering10.setSeason("Fall");
        courseOffering10.setCourseName("Java      ");
        courseOffering11.setCourseOfferingID("11");
        courseOffering11.setBuilding("1");
        courseOffering11.setRoom("11");
        courseOffering11.setTeacherID("11");
        courseOffering11.setYear("2016");
        courseOffering11.setSeason("Fall");
        courseOffering11.setCourseName("C#        ");
        courseOffering12.setCourseOfferingID("12");
        courseOffering12.setBuilding("1");
        courseOffering12.setRoom("12");
        courseOffering12.setTeacherID("12");
        courseOffering12.setYear("2016");
        courseOffering12.setSeason("Fall");
        courseOffering12.setCourseName("C++       ");
        courseOffering13.setCourseOfferingID("13");
        courseOffering13.setBuilding("1");
        courseOffering13.setRoom("13");
        courseOffering13.setTeacherID("13");
        courseOffering13.setYear("2016");
        courseOffering13.setSeason("Fall");
        courseOffering13.setCourseName("Math      ");
        courseOffering14.setCourseOfferingID("14");
        courseOffering14.setBuilding("1");
        courseOffering14.setRoom("14");
        courseOffering14.setTeacherID("14");
        courseOffering14.setYear("2016");
        courseOffering14.setSeason("Fall");
        courseOffering14.setCourseName("Statistics");
        courseOffering15.setCourseOfferingID("15");
        courseOffering15.setBuilding("1");
        courseOffering15.setRoom("15");
        courseOffering15.setTeacherID("15");
        courseOffering15.setYear("2016");
        courseOffering15.setSeason("Fall");
        courseOffering15.setCourseName("Probabilit");
        courseOffering16.setCourseOfferingID("16");
        courseOffering16.setBuilding("1");
        courseOffering16.setRoom("16");
        courseOffering16.setTeacherID("16");
        courseOffering16.setYear("2016");
        courseOffering16.setSeason("Fall");
        courseOffering16.setCourseName("Math      ");
        courseOffering17.setCourseOfferingID("17");
        courseOffering17.setBuilding("1");
        courseOffering17.setRoom("17");
        courseOffering17.setTeacherID("17");
        courseOffering17.setYear("2016");
        courseOffering17.setSeason("Fall");
        courseOffering17.setCourseName("Statistics");
        courseOffering18.setCourseOfferingID("18");
        courseOffering18.setBuilding("1");
        courseOffering18.setRoom("18");
        courseOffering18.setTeacherID("18");
        courseOffering18.setYear("2016");
        courseOffering18.setSeason("Fall");
        courseOffering18.setCourseName("Probabilit");
        courseOffering19.setCourseOfferingID("19");
        courseOffering19.setBuilding("1");
        courseOffering19.setRoom("19");
        courseOffering19.setTeacherID("19");
        courseOffering19.setYear("2016");
        courseOffering19.setSeason("Fall");
        courseOffering19.setCourseName("Mechanics ");
        courseOffering20.setCourseOfferingID("20");
        courseOffering20.setBuilding("1");
        courseOffering20.setRoom("20");
        courseOffering20.setTeacherID("20");
        courseOffering20.setYear("2016");
        courseOffering20.setSeason("Fall");
        courseOffering20.setCourseName("Electromag");
        courseOffering21.setCourseOfferingID("21");
        courseOffering21.setBuilding("1");
        courseOffering21.setRoom("21");
        courseOffering21.setTeacherID("21");
        courseOffering21.setYear("2016");
        courseOffering21.setSeason("Fall");
        courseOffering21.setCourseName("Electricit");
        courseOffering22.setCourseOfferingID("22");
        courseOffering22.setBuilding("1");
        courseOffering22.setRoom("22");
        courseOffering22.setTeacherID("22");
        courseOffering22.setYear("2016");
        courseOffering22.setSeason("Fall");
        courseOffering22.setCourseName("Mechanics ");
        courseOffering23.setCourseOfferingID("23");
        courseOffering23.setBuilding("1");
        courseOffering23.setRoom("23");
        courseOffering23.setTeacherID("23");
        courseOffering23.setYear("2016");
        courseOffering23.setSeason("Fall");
        courseOffering23.setCourseName("Electromag");
        courseOffering24.setCourseOfferingID("24");
        courseOffering24.setBuilding("1");
        courseOffering24.setRoom("24");
        courseOffering24.setTeacherID("24");
        courseOffering24.setYear("2016");
        courseOffering24.setSeason("Fall");
        courseOffering24.setCourseName("Electricit");
        courseOffering25.setCourseOfferingID("25");
        courseOffering25.setBuilding("1");
        courseOffering25.setRoom("25");
        courseOffering25.setTeacherID("25");
        courseOffering25.setYear("2016");
        courseOffering25.setSeason("Fall");
        courseOffering25.setCourseName("AED      ");
        courseOffering26.setCourseOfferingID("26");
        courseOffering26.setBuilding("1");
        courseOffering26.setRoom("26");
        courseOffering26.setTeacherID("26");
        courseOffering26.setYear("2016");
        courseOffering26.setSeason("Fall");
        courseOffering26.setCourseName("DB        ");
        courseOffering27.setCourseOfferingID("27");
        courseOffering27.setBuilding("1");
        courseOffering27.setRoom("27");
        courseOffering27.setTeacherID("27");
        courseOffering27.setYear("2016");
        courseOffering27.setSeason("Fall");
        courseOffering27.setCourseName("WEB       ");
        courseOffering28.setCourseOfferingID("28");
        courseOffering28.setBuilding("1");
        courseOffering28.setRoom("28");
        courseOffering28.setTeacherID("28");
        courseOffering28.setYear("2016");
        courseOffering28.setSeason("Fall");
        courseOffering28.setCourseName("AED       ");
        courseOffering29.setCourseOfferingID("29");
        courseOffering29.setBuilding("1");
        courseOffering29.setRoom("29");
        courseOffering29.setTeacherID("29");
        courseOffering29.setYear("2016");
        courseOffering29.setSeason("Fall");
        courseOffering29.setCourseName("DB        ");
        courseOffering30.setCourseOfferingID("30");
        courseOffering30.setBuilding("1");
        courseOffering30.setRoom("30");
        courseOffering30.setTeacherID("30");
        courseOffering30.setYear("2016");
        courseOffering30.setSeason("Fall");
        courseOffering30.setCourseName("WEB       ");
        courseOffering31.setCourseOfferingID("31");
        courseOffering31.setBuilding("1");
        courseOffering31.setRoom("31");
        courseOffering31.setTeacherID("31");
        courseOffering31.setYear("2016");
        courseOffering31.setSeason("Fall");
        courseOffering31.setCourseName("Java      ");
        courseOffering32.setCourseOfferingID("32");
        courseOffering32.setBuilding("1");
        courseOffering32.setRoom("32");
        courseOffering32.setTeacherID("32");
        courseOffering32.setYear("2016");
        courseOffering32.setSeason("Fall");
        courseOffering32.setCourseName("C#        ");
        courseOffering33.setCourseOfferingID("33");
        courseOffering33.setBuilding("1");
        courseOffering33.setRoom("33");
        courseOffering33.setTeacherID("33");
        courseOffering33.setYear("2016");
        courseOffering33.setSeason("Fall");
        courseOffering33.setCourseName("C++       ");
        courseOffering34.setCourseOfferingID("34");
        courseOffering34.setBuilding("1");
        courseOffering34.setRoom("34");
        courseOffering34.setTeacherID("34");
        courseOffering34.setYear("2016");
        courseOffering34.setSeason("Fall");
        courseOffering34.setCourseName("Java      ");
        courseOffering35.setCourseOfferingID("35");
        courseOffering35.setBuilding("1");
        courseOffering35.setRoom("35");
        courseOffering35.setTeacherID("35");
        courseOffering35.setYear("2016");
        courseOffering35.setSeason("Fall");
        courseOffering35.setCourseName("C#        ");
        courseOffering36.setCourseOfferingID("36");
        courseOffering36.setBuilding("1");
        courseOffering36.setRoom("36");
        courseOffering36.setTeacherID("36");
        courseOffering36.setYear("2016");
        courseOffering36.setSeason("Fall");
        courseOffering36.setCourseName("C++       ");
        courseOffering37.setCourseOfferingID("37");
        courseOffering37.setBuilding("1");
        courseOffering37.setRoom("37");
        courseOffering37.setTeacherID("37");
        courseOffering37.setYear("2016");
        courseOffering37.setSeason("Fall");
        courseOffering37.setCourseName("Math      ");
        courseOffering38.setCourseOfferingID("38");
        courseOffering38.setBuilding("1");
        courseOffering38.setRoom("38");
        courseOffering38.setTeacherID("38");
        courseOffering38.setYear("2016");
        courseOffering38.setSeason("Fall");
        courseOffering38.setCourseName("Statistics");
        courseOffering39.setCourseOfferingID("39");
        courseOffering39.setBuilding("1");
        courseOffering39.setRoom("39");
        courseOffering39.setTeacherID("39");
        courseOffering39.setYear("2016");
        courseOffering39.setSeason("Fall");
        courseOffering39.setCourseName("Probabilit");
        courseOffering40.setCourseOfferingID("40");
        courseOffering40.setBuilding("1");
        courseOffering40.setRoom("40");
        courseOffering40.setTeacherID("40");
        courseOffering40.setYear("2016");
        courseOffering40.setSeason("Fall");
        courseOffering40.setCourseName("Math      ");
        courseOffering41.setCourseOfferingID("41");
        courseOffering41.setBuilding("1");
        courseOffering41.setRoom("41");
        courseOffering41.setTeacherID("41");
        courseOffering41.setYear("2016");
        courseOffering41.setSeason("Fall");
        courseOffering41.setCourseName("Statistics");
        courseOffering42.setCourseOfferingID("42");
        courseOffering42.setBuilding("1");
        courseOffering42.setRoom("42");
        courseOffering42.setTeacherID("42");
        courseOffering42.setYear("2016");
        courseOffering42.setSeason("Fall");
        courseOffering42.setCourseName("Probabilit");
        courseOffering43.setCourseOfferingID("43");
        courseOffering43.setBuilding("1");
        courseOffering43.setRoom("43");
        courseOffering43.setTeacherID("43");
        courseOffering43.setYear("2016");
        courseOffering43.setSeason("Fall");
        courseOffering43.setCourseName("Mechanics ");
        courseOffering44.setCourseOfferingID("44");
        courseOffering44.setBuilding("1");
        courseOffering44.setRoom("44");
        courseOffering44.setTeacherID("44");
        courseOffering44.setYear("2016");
        courseOffering44.setSeason("Fall");
        courseOffering44.setCourseName("Electromag");
        courseOffering45.setCourseOfferingID("45");
        courseOffering45.setBuilding("1");
        courseOffering45.setRoom("45");
        courseOffering45.setTeacherID("45");
        courseOffering45.setYear("2016");
        courseOffering45.setSeason("Fall");
        courseOffering45.setCourseName("Electricit");
        courseOffering46.setCourseOfferingID("46");
        courseOffering46.setBuilding("1");
        courseOffering46.setRoom("46");
        courseOffering46.setTeacherID("46");
        courseOffering46.setYear("2016");
        courseOffering46.setSeason("Fall");
        courseOffering46.setCourseName("Mechanics ");
        courseOffering47.setCourseOfferingID("47");
        courseOffering47.setBuilding("1");
        courseOffering47.setRoom("47");
        courseOffering47.setTeacherID("47");
        courseOffering47.setYear("2016");
        courseOffering47.setSeason("Fall");
        courseOffering47.setCourseName("Electromag");
        courseOffering48.setCourseOfferingID("48");
        courseOffering48.setBuilding("1");
        courseOffering48.setRoom("48");
        courseOffering48.setTeacherID("48");
        courseOffering48.setYear("2016");
        courseOffering48.setSeason("Fall");
        courseOffering48.setCourseName("Electricit");
        
        DegreeCatalog degreeCatalog_1 = department_1.getDegreeCatalog();
        DegreeCatalog degreeCatalog_2 = department_2.getDegreeCatalog();
        DegreeCatalog degreeCatalog_3 = department_3.getDegreeCatalog();
        DegreeCatalog degreeCatalog_4 = department_4.getDegreeCatalog();
        DegreeCatalog degreeCatalog_5 = department_5.getDegreeCatalog();
        DegreeCatalog degreeCatalog_6 = department_6.getDegreeCatalog();
        DegreeCatalog degreeCatalog_7 = department_7.getDegreeCatalog();
        DegreeCatalog degreeCatalog_8 = department_8.getDegreeCatalog();
        
        Degree degree_1_1 = degreeCatalog_1.addDegree();
        Degree degree_1_2 = degreeCatalog_1.addDegree();
        Degree degree_2_1 = degreeCatalog_2.addDegree();
        Degree degree_2_2 = degreeCatalog_2.addDegree();
        Degree degree_3_1 = degreeCatalog_3.addDegree();
        Degree degree_3_2 = degreeCatalog_3.addDegree();
        Degree degree_4_1 = degreeCatalog_4.addDegree();
        Degree degree_4_2 = degreeCatalog_4.addDegree();
        Degree degree_5_1 = degreeCatalog_5.addDegree();
        Degree degree_5_2 = degreeCatalog_5.addDegree();
        Degree degree_6_1 = degreeCatalog_6.addDegree();
        Degree degree_6_2 = degreeCatalog_6.addDegree();
        Degree degree_7_1 = degreeCatalog_7.addDegree();
        Degree degree_7_2 = degreeCatalog_7.addDegree();
        Degree degree_8_1 = degreeCatalog_8.addDegree();
        Degree degree_8_2 = degreeCatalog_8.addDegree();
        
        degree_1_1.setDegreeID("1");             //NEU
        degree_1_1.setDegreeName("IS-Bachelor  ");
        degree_1_1.setDegreeRelated("IS-Master  ");
        degree_1_1.setDegreeRequirement("12 Credits");
        degree_1_2.setDegreeID("2");
        degree_1_2.setDegreeName("IS-Master    ");
        degree_1_2.setDegreeRelated("           ");
        degree_1_2.setDegreeRequirement("12 Credits");
        degree_2_1.setDegreeID("3");
        degree_2_1.setDegreeName("CS-Bachelor  ");
        degree_2_1.setDegreeRelated("CS-Master  ");
        degree_2_1.setDegreeRequirement("12 Credits");
        degree_2_2.setDegreeID("4");
        degree_2_2.setDegreeName("CS-Master    ");
        degree_2_2.setDegreeRelated("           ");
        degree_2_2.setDegreeRequirement("12 Credits");
        degree_3_1.setDegreeID("5");
        degree_3_1.setDegreeName("Math-Bachelor");
        degree_3_1.setDegreeRelated("Math-Master");
        degree_3_1.setDegreeRequirement("12 Credits");
        degree_3_2.setDegreeID("6");
        degree_3_2.setDegreeName("Math-Master  ");
        degree_3_2.setDegreeRelated("           ");
        degree_3_2.setDegreeRequirement("12 Credits");
        degree_4_1.setDegreeID("7");
        degree_4_1.setDegreeName("Phys-Bachelor");
        degree_4_1.setDegreeRelated("Phys-Master");
        degree_4_1.setDegreeRequirement("12 Credits");
        degree_4_2.setDegreeID("8");
        degree_4_2.setDegreeName("Phys-Master  ");
        degree_4_2.setDegreeRelated("           ");
        degree_4_2.setDegreeRequirement("12 Credits");   //NEU
        
        degree_5_1.setDegreeID("1");                     //BU
        degree_5_1.setDegreeName("IS-Bachelor  ");
        degree_5_1.setDegreeRelated("IS-Master  ");
        degree_5_1.setDegreeRequirement("12 Credits");
        degree_5_2.setDegreeID("2");
        degree_5_2.setDegreeName("IS-Master    ");
        degree_5_2.setDegreeRelated("           ");
        degree_5_2.setDegreeRequirement("12 Credits");
        degree_6_1.setDegreeID("3");
        degree_6_1.setDegreeName("CS-Bachelor  ");
        degree_6_1.setDegreeRelated("CS-Master  ");
        degree_6_1.setDegreeRequirement("12 Credits");
        degree_6_2.setDegreeID("4");
        degree_6_2.setDegreeName("CS-Master    ");
        degree_6_2.setDegreeRelated("           ");
        degree_6_2.setDegreeRequirement("12 Credits");
        degree_7_1.setDegreeID("5");
        degree_7_1.setDegreeName("Math-Bachelor");
        degree_7_1.setDegreeRelated("Math-Master");
        degree_7_1.setDegreeRequirement("12 Credits");
        degree_7_2.setDegreeID("6");
        degree_7_2.setDegreeName("Math-Master  ");
        degree_7_2.setDegreeRelated("           ");
        degree_7_2.setDegreeRequirement("12 Credits");
        degree_8_1.setDegreeID("7");
        degree_8_1.setDegreeName("Phys-Bachelor");
        degree_8_1.setDegreeRelated("Phys-Master");
        degree_8_1.setDegreeRequirement("12 Credits");
        degree_8_2.setDegreeID("8");
        degree_8_2.setDegreeName("Phys-Master  ");
        degree_8_2.setDegreeRelated("           ");
        degree_8_2.setDegreeRequirement("12 Credits");   //BU
        
        
        Course course1 = degree_1_1.addCourse();
        Course course2 = degree_1_1.addCourse();
        Course course3 = degree_1_1.addCourse();
        Course course4 = degree_1_2.addCourse();
        Course course5 = degree_1_2.addCourse();
        Course course6 = degree_1_2.addCourse();
        Course course7 = degree_2_1.addCourse();
        Course course8 = degree_2_1.addCourse();
        Course course9 = degree_2_1.addCourse();
        Course course10 = degree_2_2.addCourse();
        Course course11 = degree_2_2.addCourse();
        Course course12 = degree_2_2.addCourse();
        Course course13 = degree_3_1.addCourse();
        Course course14 = degree_3_1.addCourse();
        Course course15 = degree_3_1.addCourse();
        Course course16 = degree_3_2.addCourse();
        Course course17 = degree_3_2.addCourse();
        Course course18 = degree_3_2.addCourse();
        Course course19 = degree_4_1.addCourse();
        Course course20 = degree_4_1.addCourse();
        Course course21 = degree_4_1.addCourse();
        Course course22 = degree_4_2.addCourse();
        Course course23 = degree_4_2.addCourse();
        Course course24 = degree_4_2.addCourse();
        Course course25 = degree_5_1.addCourse();
        Course course26 = degree_5_1.addCourse();
        Course course27 = degree_5_1.addCourse();
        Course course28 = degree_5_2.addCourse();
        Course course29 = degree_5_2.addCourse();
        Course course30 = degree_5_2.addCourse();
        Course course31 = degree_6_1.addCourse();
        Course course32 = degree_6_1.addCourse();
        Course course33 = degree_6_1.addCourse();
        Course course34 = degree_6_2.addCourse();
        Course course35 = degree_6_2.addCourse();
        Course course36 = degree_6_2.addCourse();
        Course course37 = degree_7_1.addCourse();
        Course course38 = degree_7_1.addCourse();
        Course course39 = degree_7_1.addCourse();
        Course course40 = degree_7_2.addCourse();
        Course course41 = degree_7_2.addCourse();
        Course course42 = degree_7_2.addCourse();
        Course course43 = degree_8_1.addCourse();
        Course course44 = degree_8_1.addCourse();
        Course course45 = degree_8_1.addCourse();
        Course course46 = degree_8_2.addCourse();
        Course course47 = degree_8_2.addCourse();
        Course course48 = degree_8_2.addCourse();
        
        course1.setCourseID("1 ");
        course1.setCourseName("AED       ");
        course1.setCourseCredit("4");
        course1.setCoursePrice("200");
        course1.setCourseType("C");
        course1.setCourseDepartment("IS  ");
        course1.setCoursePrerequest("");
        course1.setCourseFollowup("");
        course1.setCourseDegreeName("Bachelor");
        course2.setCourseID("2 ");
        course2.setCourseName("DB        ");
        course2.setCourseCredit("4");
        course2.setCoursePrice("100");
        course2.setCourseType("E");
        course2.setCourseDepartment("IS  ");
        course2.setCoursePrerequest("");
        course2.setCourseFollowup("");
        course2.setCourseDegreeName("Bachelor");
        course3.setCourseID("3 ");
        course3.setCourseName("WEB       ");
        course3.setCourseCredit("4");
        course3.setCoursePrice("100");
        course3.setCourseType("E");
        course3.setCourseDepartment("IS  ");
        course3.setCoursePrerequest("");
        course3.setCourseFollowup("");
        course3.setCourseDegreeName("Bachelor");
        course4.setCourseID("4 ");
        course4.setCourseName("AED       ");
        course4.setCourseCredit("4");
        course4.setCoursePrice("400");
        course4.setCourseType("C");
        course4.setCourseDepartment("IS  ");
        course4.setCoursePrerequest("");
        course4.setCourseFollowup("");
        course4.setCourseDegreeName("Master  ");
        course5.setCourseID("5 ");
        course5.setCourseName("DB        ");
        course5.setCourseCredit("4");
        course5.setCoursePrice("200");
        course5.setCourseType("E");
        course5.setCourseDepartment("IS  ");
        course5.setCoursePrerequest("");
        course5.setCourseFollowup("");
        course5.setCourseDegreeName("Master  ");
        course6.setCourseID("6 ");
        course6.setCourseName("WEB       ");
        course6.setCourseCredit("4");
        course6.setCoursePrice("200");
        course6.setCourseType("E");
        course6.setCourseDepartment("IS  ");
        course6.setCoursePrerequest("");
        course6.setCourseFollowup("");
        course6.setCourseDegreeName("Master  ");
        course7.setCourseID("7 ");
        course7.setCourseName("Java      ");
        course7.setCourseCredit("4");
        course7.setCoursePrice("200");
        course7.setCourseType("C");
        course7.setCourseDepartment("CS  ");
        course7.setCoursePrerequest("");
        course7.setCourseFollowup("");
        course7.setCourseDegreeName("Bachelor");
        course8.setCourseID("8 ");
        course8.setCourseName("C#        ");
        course8.setCourseCredit("4");
        course8.setCoursePrice("100");
        course8.setCourseType("E");
        course8.setCourseDepartment("CS  ");
        course8.setCoursePrerequest("");
        course8.setCourseFollowup("");
        course8.setCourseDegreeName("Bachelor");
        course9.setCourseID("9 ");
        course9.setCourseName("C++       ");
        course9.setCourseCredit("4");
        course9.setCoursePrice("100");
        course9.setCourseType("E");
        course9.setCourseDepartment("CS  ");
        course9.setCoursePrerequest("");
        course9.setCourseFollowup("");
        course9.setCourseDegreeName("Bachelor");
        course10.setCourseID("10");
        course10.setCourseName("Java      ");
        course10.setCourseCredit("4");
        course10.setCoursePrice("400");
        course10.setCourseType("C");
        course10.setCourseDepartment("CS  ");
        course10.setCoursePrerequest("");
        course10.setCourseFollowup("");
        course10.setCourseDegreeName("Master  ");
        course11.setCourseID("11");
        course11.setCourseName("C#        ");
        course11.setCourseCredit("4");
        course11.setCoursePrice("200");
        course11.setCourseType("E");
        course11.setCourseDepartment("CS  ");
        course11.setCoursePrerequest("");
        course11.setCourseFollowup("");
        course11.setCourseDegreeName("Master  ");
        course12.setCourseID("12");
        course12.setCourseName("C++       ");
        course12.setCourseCredit("4");
        course12.setCoursePrice("200");
        course12.setCourseType("E");
        course12.setCourseDepartment("CS  ");
        course12.setCoursePrerequest("");
        course12.setCourseFollowup("");
        course12.setCourseDegreeName("Master  ");
        course13.setCourseID("13");
        course13.setCourseName("Math      ");
        course13.setCourseCredit("4");
        course13.setCoursePrice("200");
        course13.setCourseType("C");
        course13.setCourseDepartment("Math");
        course13.setCoursePrerequest("");
        course13.setCourseFollowup("");
        course13.setCourseDegreeName("Bachelor");
        course14.setCourseID("14");
        course14.setCourseName("Statistics");
        course14.setCourseCredit("4");
        course14.setCoursePrice("100");
        course14.setCourseType("E");
        course14.setCourseDepartment("Math");
        course14.setCoursePrerequest("");
        course14.setCourseFollowup("");
        course14.setCourseDegreeName("Bachelor");
        course15.setCourseID("15");
        course15.setCourseName("Probabilit");
        course15.setCourseCredit("4");
        course15.setCoursePrice("100");
        course15.setCourseType("E");
        course15.setCourseDepartment("Math");
        course15.setCoursePrerequest("");
        course15.setCourseFollowup("");
        course15.setCourseDegreeName("Bachelor");
        course16.setCourseID("16");
        course16.setCourseName("Math      ");
        course16.setCourseCredit("4");
        course16.setCoursePrice("400");
        course16.setCourseType("C");
        course16.setCourseDepartment("Math");
        course16.setCoursePrerequest("");
        course16.setCourseFollowup("");
        course16.setCourseDegreeName("Master  ");
        course17.setCourseID("17");
        course17.setCourseName("Statistics");
        course17.setCourseCredit("4");
        course17.setCoursePrice("200");
        course17.setCourseType("E");
        course17.setCourseDepartment("Math");
        course17.setCoursePrerequest("");
        course17.setCourseFollowup("");
        course17.setCourseDegreeName("Master  ");
        course18.setCourseID("18");
        course18.setCourseName("Probabilit");
        course18.setCourseCredit("4");
        course18.setCoursePrice("200");
        course18.setCourseType("E");
        course18.setCourseDepartment("Math");
        course18.setCoursePrerequest("");
        course18.setCourseFollowup("");
        course18.setCourseDegreeName("Master  ");
        course19.setCourseID("19");
        course19.setCourseName("Mechanics ");
        course19.setCourseCredit("4");
        course19.setCoursePrice("200");
        course19.setCourseType("C");
        course19.setCourseDepartment("Phys");
        course19.setCoursePrerequest("");
        course19.setCourseFollowup("");
        course19.setCourseDegreeName("Bachelor");
        course20.setCourseID("20");
        course20.setCourseName("Electromag");
        course20.setCourseCredit("4");
        course20.setCoursePrice("100");
        course20.setCourseType("E");
        course20.setCourseDepartment("Phys");
        course20.setCoursePrerequest("");
        course20.setCourseFollowup("");
        course20.setCourseDegreeName("Bachelor");
        course21.setCourseID("21");
        course21.setCourseName("Electricit");
        course21.setCourseCredit("4");
        course21.setCoursePrice("100");
        course21.setCourseType("E");
        course21.setCourseDepartment("Phys");
        course21.setCoursePrerequest("");
        course21.setCourseFollowup("");
        course21.setCourseDegreeName("Bachelor");
        course22.setCourseID("22");
        course22.setCourseName("Mechanics ");
        course22.setCourseCredit("4");
        course22.setCoursePrice("400");
        course22.setCourseType("C");
        course22.setCourseDepartment("Phys");
        course22.setCoursePrerequest("");
        course22.setCourseFollowup("");
        course22.setCourseDegreeName("Master  ");
        course23.setCourseID("23");
        course23.setCourseName("Electromag");
        course23.setCourseCredit("4");
        course23.setCoursePrice("200");
        course23.setCourseType("E");
        course23.setCourseDepartment("Phys");
        course23.setCoursePrerequest("");
        course23.setCourseFollowup("");
        course23.setCourseDegreeName("Master  ");
        course24.setCourseID("24");
        course24.setCourseName("Electricit");
        course24.setCourseCredit("4");
        course24.setCoursePrice("200");
        course24.setCourseType("E");
        course24.setCourseDepartment("Phys");
        course24.setCoursePrerequest("");
        course24.setCourseFollowup("");
        course24.setCourseDegreeName("Master  ");
        course25.setCourseID("1 ");
        course25.setCourseName("AED       ");
        course25.setCourseCredit("4");
        course25.setCoursePrice("200");
        course25.setCourseType("C");
        course25.setCourseDepartment("IS  ");
        course25.setCoursePrerequest("");
        course25.setCourseFollowup("");
        course25.setCourseDegreeName("Bachelor");
        course26.setCourseID("2 ");
        course26.setCourseName("DB        ");
        course26.setCourseCredit("4");
        course26.setCoursePrice("100");
        course26.setCourseType("E");
        course26.setCourseDepartment("IS  ");
        course26.setCoursePrerequest("");
        course26.setCourseFollowup("");
        course26.setCourseDegreeName("Bachelor");
        course27.setCourseID("3 ");
        course27.setCourseName("WEB       ");
        course27.setCourseCredit("4");
        course27.setCoursePrice("100");
        course27.setCourseType("E");
        course27.setCourseDepartment("IS  ");
        course27.setCoursePrerequest("");
        course27.setCourseFollowup("");
        course27.setCourseDegreeName("Bachelor");
        course28.setCourseID("4 ");
        course28.setCourseName("AED       ");
        course28.setCourseCredit("4");
        course28.setCoursePrice("400");
        course28.setCourseType("C");
        course28.setCourseDepartment("IS  ");
        course28.setCoursePrerequest("");
        course28.setCourseFollowup("");
        course28.setCourseDegreeName("Master  ");
        course29.setCourseID("5 ");
        course29.setCourseName("DB        ");
        course29.setCourseCredit("4");
        course29.setCoursePrice("200");
        course29.setCourseType("E");
        course29.setCourseDepartment("IS  ");
        course29.setCoursePrerequest("");
        course29.setCourseFollowup("");
        course29.setCourseDegreeName("Master  ");
        course30.setCourseID("6 ");
        course30.setCourseName("WEB       ");
        course30.setCourseCredit("4");
        course30.setCoursePrice("200");
        course30.setCourseType("E");
        course30.setCourseDepartment("IS  ");
        course30.setCoursePrerequest("");
        course30.setCourseFollowup("");
        course30.setCourseDegreeName("Master  ");
        course31.setCourseID("7 ");
        course31.setCourseName("Java      ");
        course31.setCourseCredit("4");
        course31.setCoursePrice("200");
        course31.setCourseType("C");
        course31.setCourseDepartment("CS  ");
        course31.setCoursePrerequest("");
        course31.setCourseFollowup("");
        course31.setCourseDegreeName("Bachelor");
        course32.setCourseID("8 ");
        course32.setCourseName("C#        ");
        course32.setCourseCredit("4");
        course32.setCoursePrice("100");
        course32.setCourseType("E");
        course32.setCourseDepartment("CS  ");
        course32.setCoursePrerequest("");
        course32.setCourseFollowup("");
        course32.setCourseDegreeName("Bachelor");
        course33.setCourseID("9 ");
        course33.setCourseName("C++       ");
        course33.setCourseCredit("4");
        course33.setCoursePrice("100");
        course33.setCourseType("E");
        course33.setCourseDepartment("CS  ");
        course33.setCoursePrerequest("");
        course33.setCourseFollowup("");
        course33.setCourseDegreeName("Bachelor");
        course34.setCourseID("10");
        course34.setCourseName("Java      ");
        course34.setCourseCredit("4");
        course34.setCoursePrice("400");
        course34.setCourseType("C");
        course34.setCourseDepartment("CS  ");
        course34.setCoursePrerequest("");
        course34.setCourseFollowup("");
        course34.setCourseDegreeName("Master  ");
        course35.setCourseID("11");
        course35.setCourseName("C#        ");
        course35.setCourseCredit("4");
        course35.setCoursePrice("200");
        course35.setCourseType("E");
        course35.setCourseDepartment("CS  ");
        course35.setCoursePrerequest("");
        course35.setCourseFollowup("");
        course35.setCourseDegreeName("Master  ");
        course36.setCourseID("12");
        course36.setCourseName("C++       ");
        course36.setCourseCredit("4");
        course36.setCoursePrice("200");
        course36.setCourseType("E");
        course36.setCourseDepartment("CS  ");
        course36.setCoursePrerequest("");
        course36.setCourseFollowup("");
        course36.setCourseDegreeName("Master  ");
        course37.setCourseID("13");
        course37.setCourseName("Math      ");
        course37.setCourseCredit("4");
        course37.setCoursePrice("200");
        course37.setCourseType("C");
        course37.setCourseDepartment("Math");
        course37.setCoursePrerequest("");
        course37.setCourseFollowup("");
        course37.setCourseDegreeName("Bachelor");
        course38.setCourseID("14");
        course38.setCourseName("Statistics");
        course38.setCourseCredit("4");
        course38.setCoursePrice("100");
        course38.setCourseType("E");
        course38.setCourseDepartment("Math");
        course38.setCoursePrerequest("");
        course38.setCourseFollowup("");
        course38.setCourseDegreeName("Bachelor");
        course39.setCourseID("15");
        course39.setCourseName("Probabilit");
        course39.setCourseCredit("4");
        course39.setCoursePrice("100");
        course39.setCourseType("E");
        course39.setCourseDepartment("Math");
        course39.setCoursePrerequest("");
        course39.setCourseFollowup("");
        course39.setCourseDegreeName("Bachelor");
        course40.setCourseID("16");
        course40.setCourseName("Math      ");
        course40.setCourseCredit("4");
        course40.setCoursePrice("400");
        course40.setCourseType("C");
        course40.setCourseDepartment("Math");
        course40.setCoursePrerequest("");
        course40.setCourseFollowup("");
        course40.setCourseDegreeName("Master  ");
        course41.setCourseID("17");
        course41.setCourseName("Statistics");
        course41.setCourseCredit("4");
        course41.setCoursePrice("200");
        course41.setCourseType("E");
        course41.setCourseDepartment("Math");
        course41.setCoursePrerequest("");
        course41.setCourseFollowup("");
        course41.setCourseDegreeName("Master  ");
        course42.setCourseID("18");
        course42.setCourseName("Probabilit");
        course42.setCourseCredit("4");
        course42.setCoursePrice("200");
        course42.setCourseType("E");
        course42.setCourseDepartment("Math");
        course42.setCoursePrerequest("");
        course42.setCourseFollowup("");
        course42.setCourseDegreeName("Master  ");
        course43.setCourseID("19");
        course43.setCourseName("Mechanics ");
        course43.setCourseCredit("4");
        course43.setCoursePrice("200");
        course43.setCourseType("C");
        course43.setCourseDepartment("Phys");
        course43.setCoursePrerequest("");
        course43.setCourseFollowup("");
        course43.setCourseDegreeName("Bachelor");
        course44.setCourseID("20");
        course44.setCourseName("Electromag");
        course44.setCourseCredit("4");
        course44.setCoursePrice("100");
        course44.setCourseType("E");
        course44.setCourseDepartment("Phys");
        course44.setCoursePrerequest("");
        course44.setCourseFollowup("");
        course44.setCourseDegreeName("Bachelor");
        course45.setCourseID("21");
        course45.setCourseName("Electricit");
        course45.setCourseCredit("4");
        course45.setCoursePrice("100");
        course45.setCourseType("E");
        course45.setCourseDepartment("Phys");
        course45.setCoursePrerequest("");
        course45.setCourseFollowup("");
        course45.setCourseDegreeName("Bachelor");
        course46.setCourseID("22");
        course46.setCourseName("Mechanics ");
        course46.setCourseCredit("4");
        course46.setCoursePrice("400");
        course46.setCourseType("C");
        course46.setCourseDepartment("Phys");
        course46.setCoursePrerequest("");
        course46.setCourseFollowup("");
        course46.setCourseDegreeName("Master  ");
        course47.setCourseID("23");
        course47.setCourseName("Electromag");
        course47.setCourseCredit("4");
        course47.setCoursePrice("200");
        course47.setCourseType("E");
        course47.setCourseDepartment("Phys");
        course47.setCoursePrerequest("");
        course47.setCourseFollowup("");
        course47.setCourseDegreeName("Master  ");
        course48.setCourseID("24");
        course48.setCourseName("Electricit");
        course48.setCourseCredit("4");
        course48.setCoursePrice("200");
        course48.setCourseType("E");
        course48.setCourseDepartment("Phys");
        course48.setCoursePrerequest("");
        course48.setCourseFollowup("");
        course48.setCourseDegreeName("Master  ");
        
        
        return universityCatalog;
    }
    
    public static StudentDirectory Initialization_Student() {
        
        StudentDirectory studentList = new StudentDirectory();
        Student student_1 = studentList.addStudent();
        Student student_2 = studentList.addStudent();
        Student student_3 = studentList.addStudent();
        Student student_4 = studentList.addStudent();
        Student student_5 = studentList.addStudent();
        Student student_6 = studentList.addStudent();
        Student student_7 = studentList.addStudent();
        Student student_8 = studentList.addStudent();
        Student student_9 = studentList.addStudent();
        Student student_10 = studentList.addStudent();
        Student student_11 = studentList.addStudent();
        Student student_12 = studentList.addStudent();
        Student student_13 = studentList.addStudent();
        Student student_14 = studentList.addStudent();
        Student student_15 = studentList.addStudent();
        Student student_16 = studentList.addStudent();
        
        student_1.setFirstName("Shuchao");
        student_1.setLastName("Huang");
        student_1.setGender("M");
        student_1.setDateOfBirth("1992-10-06");
        student_1.setEmail("123456@");
        student_1.setAddress("75 Saint St");
        student_1.setZipcode("31000");
        student_1.setYearOfEntrance("2016");
        student_1.setSeasonOfEntrance("Fall");
        student_1.setUniversityName("NEU");
        student_1.setCollegeName("COE");
        student_1.setDepartmentName("IS  ");
        student_1.setStudentID("1");
        
        student_2.setFirstName("Zeqiang");
        student_2.setLastName("Li   ");
        student_2.setGender("M");
        student_2.setDateOfBirth("1992-10-07");
        student_2.setEmail("123456@");
        student_2.setAddress("76 Saint St");
        student_2.setZipcode("31001");
        student_2.setYearOfEntrance("2016");
        student_2.setSeasonOfEntrance("Fall");
        student_2.setUniversityName("NEU");
        student_2.setCollegeName("COE");
        student_2.setDepartmentName("IS  ");
        student_2.setStudentID("2");
        
        student_3.setFirstName("Fanqi  ");
        student_3.setLastName("Zheng");
        student_3.setGender("M");
        student_3.setDateOfBirth("1992-10-08");
        student_3.setEmail("123456@");
        student_3.setAddress("77 Saint St");
        student_3.setZipcode("31002");
        student_3.setYearOfEntrance("2016");
        student_3.setSeasonOfEntrance("Fall");
        student_3.setUniversityName("NEU");
        student_3.setCollegeName("COE");
        student_3.setDepartmentName("CS  ");
        student_3.setStudentID("3");
        
        student_4.setFirstName("Jiamin ");
        student_4.setLastName("Wang ");
        student_4.setGender("F");
        student_4.setDateOfBirth("1992-10-10");
        student_4.setEmail("123456@");
        student_4.setAddress("78 Saint St");
        student_4.setZipcode("31004");
        student_4.setYearOfEntrance("2016");
        student_4.setSeasonOfEntrance("Fall");
        student_4.setUniversityName("NEU");
        student_4.setCollegeName("COE");
        student_4.setDepartmentName("CS  ");
        student_4.setStudentID("4");
        
        student_5.setFirstName("Jiayuan");
        student_5.setLastName("Chen ");
        student_5.setGender("F");
        student_5.setDateOfBirth("1992-10-11");
        student_5.setEmail("123456@");
        student_5.setAddress("80 Saint St");
        student_5.setZipcode("31006");
        student_5.setYearOfEntrance("2016");
        student_5.setSeasonOfEntrance("Fall");
        student_5.setUniversityName("NEU");
        student_5.setCollegeName("COS");
        student_5.setDepartmentName("Math");
        student_5.setStudentID("5");
        
        student_6.setFirstName("Kuai   ");
        student_6.setLastName("Hu   ");
        student_6.setGender("M");
        student_6.setDateOfBirth("1992-11-06");
        student_6.setEmail("123456@");
        student_6.setAddress("75 Saint St");
        student_6.setZipcode("31000");
        student_6.setYearOfEntrance("2016");
        student_6.setSeasonOfEntrance("Fall");
        student_6.setUniversityName("NEU");
        student_6.setCollegeName("COS");
        student_6.setDepartmentName("Math");
        student_6.setStudentID("6");
        
        student_7.setFirstName("Xing   ");
        student_7.setLastName("Yang ");
        student_7.setGender("M");
        student_7.setDateOfBirth("1992-12-06");
        student_7.setEmail("123456@");
        student_7.setAddress("75 Saint St");
        student_7.setZipcode("31000");
        student_7.setYearOfEntrance("2016");
        student_7.setSeasonOfEntrance("Fall");
        student_7.setUniversityName("NEU");
        student_7.setCollegeName("COS");
        student_7.setDepartmentName("Phys");
        student_7.setStudentID("7");
        
        student_8.setFirstName("Yeqing ");
        student_8.setLastName("Guan ");
        student_8.setGender("M");
        student_8.setDateOfBirth("1993-01-17");
        student_8.setEmail("123456@");
        student_8.setAddress("75 Saint St");
        student_8.setZipcode("31000");
        student_8.setYearOfEntrance("2016");
        student_8.setSeasonOfEntrance("Fall");
        student_8.setUniversityName("NEU");
        student_8.setCollegeName("COS");
        student_8.setDepartmentName("Phys");
        student_8.setStudentID("8");
        
        student_9.setFirstName("Ying   ");
        student_9.setLastName("Wang ");
        student_9.setGender("F");
        student_9.setDateOfBirth("1991-08-06");
        student_9.setEmail("123456@");
        student_9.setAddress("83 Saint St");
        student_9.setZipcode("31010");
        student_9.setYearOfEntrance("2016");
        student_9.setSeasonOfEntrance("Fall");
        student_9.setUniversityName("BU ");
        student_9.setCollegeName("COE");
        student_9.setDepartmentName("IS  ");
        student_9.setStudentID("1");
        
        student_10.setFirstName("Lu     ");
        student_10.setLastName("Yang ");
        student_10.setGender("F");
        student_10.setDateOfBirth("1992-12-09");
        student_10.setEmail("123456@");
        student_10.setAddress("72 Saint St");
        student_10.setZipcode("31011");
        student_10.setYearOfEntrance("2016");
        student_10.setSeasonOfEntrance("Fall");
        student_10.setUniversityName("BU ");
        student_10.setCollegeName("COE");
        student_10.setDepartmentName("IS  ");
        student_10.setStudentID("2");
        
        student_11.setFirstName("Yue    ");
        student_11.setLastName("Liu  ");
        student_11.setGender("F");
        student_11.setDateOfBirth("1992-07-05");
        student_11.setEmail("123456@");
        student_11.setAddress("71 Saint St");
        student_11.setZipcode("31013");
        student_11.setYearOfEntrance("2016");
        student_11.setSeasonOfEntrance("Fall");
        student_11.setUniversityName("BU ");
        student_11.setCollegeName("COE");
        student_11.setDepartmentName("CS  ");
        student_11.setStudentID("3");
        
        student_12.setFirstName("Chris  ");
        student_12.setLastName("Paul ");
        student_12.setGender("M");
        student_12.setDateOfBirth("1990-10-06");
        student_12.setEmail("123456@");
        student_12.setAddress("90 Saint St");
        student_12.setZipcode("31020");
        student_12.setYearOfEntrance("2016");
        student_12.setSeasonOfEntrance("Fall");
        student_12.setUniversityName("BU ");
        student_12.setCollegeName("COE");
        student_12.setDepartmentName("CS  ");
        student_12.setStudentID("4");
        
        student_13.setFirstName("Dwyane ");
        student_13.setLastName("Wade ");
        student_13.setGender("M");
        student_13.setDateOfBirth("1990-09-06");
        student_13.setEmail("123456@");
        student_13.setAddress("91 Saint St");
        student_13.setZipcode("31021");
        student_13.setYearOfEntrance("2016");
        student_13.setSeasonOfEntrance("Fall");
        student_13.setUniversityName("BU ");
        student_13.setCollegeName("COS");
        student_13.setDepartmentName("Math");
        student_13.setStudentID("5");
        
        student_14.setFirstName("Vince  ");
        student_14.setLastName("Cater");
        student_14.setGender("M");
        student_14.setDateOfBirth("1989-10-06");
        student_14.setEmail("123456@");
        student_14.setAddress("92 Saint St");
        student_14.setZipcode("31022");
        student_14.setYearOfEntrance("2016");
        student_14.setSeasonOfEntrance("Fall");
        student_14.setUniversityName("BU ");
        student_14.setCollegeName("COS");
        student_14.setDepartmentName("Math");
        student_14.setStudentID("6");
        
        student_15.setFirstName("Ming   ");
        student_15.setLastName("Yao  ");
        student_15.setGender("M");
        student_15.setDateOfBirth("1988-10-06");
        student_15.setEmail("123456@");
        student_15.setAddress("93 Saint St");
        student_15.setZipcode("31023");
        student_15.setYearOfEntrance("2016");
        student_15.setSeasonOfEntrance("Fall");
        student_15.setUniversityName("BU ");
        student_15.setCollegeName("COS");
        student_15.setDepartmentName("Phys");
        student_15.setStudentID("7");
        
        student_16.setFirstName("Ray    ");
        student_16.setLastName("Allen");
        student_16.setGender("M");
        student_16.setDateOfBirth("1987-01-06");
        student_16.setEmail("123456@");
        student_16.setAddress("95 Saint St");
        student_16.setZipcode("31025");
        student_16.setYearOfEntrance("2016");
        student_16.setSeasonOfEntrance("Fall");
        student_16.setUniversityName("BU ");
        student_16.setCollegeName("COS");
        student_16.setDepartmentName("Phys");
        student_16.setStudentID("8");
        
        return studentList;
    }
    
}
