/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Person.Resume;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Eric
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private Resume resume;
    
    public CreateJPanel(Resume resume) {
        initComponents();
        
        ImageJLable.setBorder(BorderFactory.createLineBorder(Color.black));

        this.resume = resume;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CreateCoverPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FnameTextF = new javax.swing.JTextField();
        LnameTextF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EmailTextF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MobileTextF = new javax.swing.JTextField();
        MonthBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        AffilTextF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddressTextF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AptTextF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CityTextF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MajorTextF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ZipTextF = new javax.swing.JTextField();
        CountryBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        DegreeBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        EndTextF = new javax.swing.JTextField();
        StartTextF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        Skill_1TextF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Level_1Box = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatementTextArea = new javax.swing.JTextArea();
        CreateBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        GenderBox = new javax.swing.JComboBox<>();
        Upload = new javax.swing.JButton();
        ImageJLable = new javax.swing.JLabel();
        YearBox = new javax.swing.JComboBox<>();
        DateBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        NationBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        Skill_2TextF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Level_2Box = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        Skill_3TextF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Level_3Box = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setText("Create Your Own Resume");

        jLabel2.setText("FirstName:");

        jLabel3.setText("LastName:");

        FnameTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameTextFActionPerformed(evt);
            }
        });

        LnameTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTextFActionPerformed(evt);
            }
        });

        jLabel4.setText("Gender:");

        jLabel5.setText("BirthDate:");

        jLabel6.setText("Year");

        jLabel7.setText("month");

        jLabel8.setText("date");

        jLabel9.setText("Mobile:");

        jLabel10.setText("E-mail:");

        MonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        MonthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Affiliation:");

        jLabel12.setText("Address:");

        jLabel13.setText("Apt:");

        jLabel14.setText("City:");

        jLabel15.setText("Country:");

        jLabel16.setText("Zipcode:");

        CountryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US", "China" }));

        jLabel17.setText("Degree:");

        DegreeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor", "Master", "PhD", "MBA", "DBA", "Others" }));

        jLabel18.setText("Major:");

        jLabel19.setText("End:");

        jLabel20.setText("Start:");

        jLabel21.setText("Skills:");

        jLabel22.setText("Level:");

        Level_1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Familiar", "Good", "Master" }));

        jLabel23.setText("Make Your Personal Statement:");

        StatementTextArea.setColumns(20);
        StatementTextArea.setRows(5);
        jScrollPane2.setViewportView(StatementTextArea);

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        Upload.setText("Upload Photo");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        ImageJLable.setBackground(new java.awt.Color(255, 255, 255));
        ImageJLable.setSize(new java.awt.Dimension(50, 50));

        YearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        DateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel24.setText("Nation:");

        NationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US", "China", "India" }));

        jLabel25.setText("Skills:");

        jLabel26.setText("Level:");

        Level_2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Familiar", "Good", "Master" }));

        jLabel27.setText("Skills:");

        jLabel28.setText("Level:");

        Level_3Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Familiar", "Good", "Master" }));

        javax.swing.GroupLayout CreateCoverPanelLayout = new javax.swing.GroupLayout(CreateCoverPanel);
        CreateCoverPanel.setLayout(CreateCoverPanelLayout);
        CreateCoverPanelLayout.setHorizontalGroup(
            CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(StartTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(DegreeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel18)))
                                .addGap(18, 18, 18)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MajorTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EndTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(Skill_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel22))
                                    .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createSequentialGroup()
                                            .addGap(232, 232, 232)
                                            .addComponent(CreateBtn)
                                            .addGap(205, 205, 205))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23))))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(AddressTextF)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateCoverPanelLayout.createSequentialGroup()
                                                .addGap(118, 118, 118)
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 67, Short.MAX_VALUE)))
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CountryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel4))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(GenderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FnameTextF)
                                        .addComponent(NationBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(19, 19, 19)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(YearBox, 0, 1, Short.MAX_VALUE)
                                            .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DateBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)))
                                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Upload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCoverPanelLayout.createSequentialGroup()
                                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(16, 16, 16))))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(18, 18, 18)
                                    .addComponent(Skill_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel26))
                                .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                    .addGap(424, 424, 424)
                                    .addComponent(Level_2Box, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Level_1Box, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(18, 18, 18)
                                    .addComponent(Skill_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel28))
                                .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                                    .addGap(424, 424, 424)
                                    .addComponent(Level_3Box, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        CreateCoverPanelLayout.setVerticalGroup(
            CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(NationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateCoverPanelLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upload)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DegreeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(MajorTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(StartTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(EndTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Skill_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Level_1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Skill_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(Level_2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Skill_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(Level_3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateBtn)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(CreateCoverPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FnameTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameTextFActionPerformed

    private void LnameTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTextFActionPerformed

    private void MonthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthBoxActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:

        try
        {
            int mobile = Integer.parseInt(MobileTextF.getText());
//            resume.setPhone(mobile);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Insert Right Phone Number");
        }
        
        try
        {
            int zip = Integer.parseInt(ZipTextF.getText());
//            resume.setZipcode(zip);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Insert Right Zipcode");
        }
        
        try
        {
            resume.setFirstname(FnameTextF.getText());
            resume.setLastname(LnameTextF.getText());
            resume.setGender(GenderBox.getSelectedItem().toString());
            resume.setNation(NationBox.getSelectedItem().toString());
            resume.setBirthday_year(YearBox.getSelectedItem().toString());
            resume.setBirthday_month(MonthBox.getSelectedItem().toString());
            resume.setBirthday_date(DateBox.getSelectedItem().toString());
            resume.setAddress(AddressTextF.getText());
            resume.setApt(AptTextF.getText());
            resume.setCity(CityTextF.getText());
            resume.setCountry(CountryBox.getSelectedItem().toString());
            resume.setAffiliation(AffilTextF.getText());
            resume.setEdu_degree(DegreeBox.getSelectedItem().toString());
            resume.setMajor(MajorTextF.getText());
            resume.setEdu_date_1(StartTextF.getText());
            resume.setEdu_date_2(EndTextF.getText());
//            resume.setPhone(MobileTextF.getText());
            resume.setEmail(EmailTextF.getText());
            resume.setSkill_1(Skill_1TextF.getText());
            resume.setLevel_1(Level_1Box.getSelectedItem().toString());
            resume.setSkill_2(Skill_2TextF.getText());
            resume.setLevel_2(Level_2Box.getSelectedItem().toString());
            resume.setSkill_3(Skill_3TextF.getText());
            resume.setLevel_3(Level_3Box.getSelectedItem().toString());
            resume.setStatement(StatementTextArea.getText());
            
            int zip = Integer.parseInt(ZipTextF.getText());
            resume.setZipcode(zip);
            int mobile = Integer.parseInt(MobileTextF.getText());
            resume.setPhone(mobile);
            
            JOptionPane.showMessageDialog(null,"Resume Created Successfully");
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Resume Created Failed");
        } 
    }//GEN-LAST:event_CreateBtnActionPerformed
    
    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        // TODO add your handling code here:

        JFileChooser FChooser = new JFileChooser();
        int ReturnValue = FChooser.showOpenDialog(null);
        if(ReturnValue == JFileChooser.APPROVE_OPTION)
        {
            File selected = FChooser.getSelectedFile();
            resume.setImage(selected.getAbsolutePath());

            String path = resume.getImage();
            ImageIcon ThisImg = new ImageIcon(path);

            Image img1 = ThisImg.getImage().getScaledInstance(107, 107, WIDTH);
            ImageIcon img2 = new ImageIcon(img1);
            ImageJLable.setIcon(img2);

        }

    }//GEN-LAST:event_UploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextF;
    private javax.swing.JTextField AffilTextF;
    private javax.swing.JTextField AptTextF;
    private javax.swing.JTextField CityTextF;
    private javax.swing.JComboBox<String> CountryBox;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JPanel CreateCoverPanel;
    private javax.swing.JComboBox<String> DateBox;
    private javax.swing.JComboBox<String> DegreeBox;
    private javax.swing.JTextField EmailTextF;
    private javax.swing.JTextField EndTextF;
    private javax.swing.JTextField FnameTextF;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel ImageJLable;
    private javax.swing.JComboBox<String> Level_1Box;
    private javax.swing.JComboBox<String> Level_2Box;
    private javax.swing.JComboBox<String> Level_3Box;
    private javax.swing.JTextField LnameTextF;
    private javax.swing.JTextField MajorTextF;
    private javax.swing.JTextField MobileTextF;
    private javax.swing.JComboBox<String> MonthBox;
    private javax.swing.JComboBox<String> NationBox;
    private javax.swing.JTextField Skill_1TextF;
    private javax.swing.JTextField Skill_2TextF;
    private javax.swing.JTextField Skill_3TextF;
    private javax.swing.JTextField StartTextF;
    private javax.swing.JTextArea StatementTextArea;
    private javax.swing.JButton Upload;
    private javax.swing.JComboBox<String> YearBox;
    private javax.swing.JTextField ZipTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
