/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Person.Resume;
import java.awt.Color;
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author Eric
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VieJPanel
     */
    public ViewJPanel(Resume resume) {
        initComponents();
        
        ImageJLable.setBorder(BorderFactory.createLineBorder(Color.black));
        
        displayResume(resume);
        
    }
    
    
    public void displayResume(Resume resume)
    {
        String Fname = resume.getFirstname();
        FnameTextF.setText(Fname);
        String Lname = resume.getLastname();
        LnameTextF.setText(Lname);
        String Gender = resume.getGender();
        GenderTextF.setText(Gender);
        String Nation = resume.getNation();
        NationTextF.setText(Nation);
        String BirthYear = resume.getBirthday_year();
        YearTextF.setText(BirthYear);
        String BirthMonth = resume.getBirthday_month();
        MonthTextF.setText(BirthMonth);
        String BirthDate = resume.getBirthday_date();
        DateTextF.setText(BirthDate);
        String Address = resume.getAddress();
        AddressTextF.setText(Address);
        String Apt = resume.getApt();
        AptTextF.setText(Apt);
        String City = resume.getCity();
        CityTextF.setText(City);

        int zip = resume.getZipcode();
        String newzip = String.valueOf(zip);
        ZipTextF.setText(newzip);
        
        String Country = resume.getCountry();
        CountryTextF.setText(Country);
        String Affiliation = resume.getAffiliation();
        AffilTextF.setText(Affiliation);
        String Degree = resume.getEdu_degree();
        DegreeTextF.setText(Degree);
        String Major = resume.getMajor();
        MajorTextF.setText(Major);
        String Start = resume.getEdu_date_1();
        StartTextF.setText(Start);
        String End = resume.getEdu_date_2();
        EndTextF.setText(End);
        
//        String Phone = resume.getPhone();
//        MobileTextF.setText(Phone);
        int mobile = resume.getPhone();
        String newmobile = String.valueOf(mobile);
        MobileTextF.setText(newmobile);

        String Email = resume.getEmail();
        EmailTextF.setText(Email);
        String Skill_1 = resume.getSkill_1();
        Skill_1TextF.setText(Skill_1);
        String Level_1 = resume.getLevel_1();
        Level_1TextF.setText(Level_1);
        String Skill_2 = resume.getSkill_2();
        Skill_2TextF.setText(Skill_2);
        String Level_2 = resume.getLevel_2();
        Level_2TextF.setText(Level_2);
        String Skill_3 = resume.getSkill_3();
        Skill_3TextF.setText(Skill_3);
        String Level_3 = resume.getLevel_3();
        Level_3TextF.setText(Level_3);
        String Statement = resume.getStatement();
        StatementTextArea.setText(Statement);
        
        String path = resume.getImage();
        ImageIcon ThisImg = new ImageIcon(path);
        ImageJLable.setIcon(ThisImg);
        
        Image img1 = ThisImg.getImage().getScaledInstance(107, 107, WIDTH);
        ImageIcon img2 = new ImageIcon(img1);
        ImageJLable.setIcon(img2);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ViewCoverPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FnameTextF = new javax.swing.JTextField();
        LnameTextF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DateTextF = new javax.swing.JTextField();
        YearTextF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EmailTextF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MobileTextF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AffilTextF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AddressTextF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AptTextF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CityTextF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MajorTextF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ZipTextF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        EndTextF = new javax.swing.JTextField();
        StartTextF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        Skill_1TextF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatementTextArea = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        GenderTextF = new javax.swing.JTextField();
        MonthTextF = new javax.swing.JTextField();
        CountryTextF = new javax.swing.JTextField();
        DegreeTextF = new javax.swing.JTextField();
        Level_1TextF = new javax.swing.JTextField();
        ImageJLable = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NationTextF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Skill_2TextF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Level_2TextF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Skill_3TextF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Level_3TextF = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setText("View  Resume");

        jLabel2.setText("FirstName:");

        jLabel3.setText("LastName:");

        FnameTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameTextFActionPerformed(evt);
            }
        });

        LnameTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTextFActionPerformed(evt);
            }
        });

        jLabel4.setText("Gender:");

        jLabel5.setText("BirthDate:");

        jLabel6.setText("Year");

        jLabel7.setText("month");

        jLabel8.setText("date");

        jLabel9.setText("Mobile:");

        jLabel10.setText("E-mail:");

        jLabel11.setText("Affiliation:");

        jLabel12.setText("Address:");

        jLabel13.setText("Apt:");

        jLabel14.setText("City:");

        jLabel15.setText("Country:");

        jLabel16.setText("Zipcode:");

        jLabel17.setText("Degree:");

        jLabel18.setText("Major:");

        jLabel19.setText("End:");

        jLabel20.setText("Start:");

        jLabel21.setText("Skills:");

        jLabel22.setText("Level:");

        jLabel23.setText("Your Personal Statement:");

        StatementTextArea.setColumns(20);
        StatementTextArea.setRows(5);
        jScrollPane2.setViewportView(StatementTextArea);

        ImageJLable.setBackground(new java.awt.Color(255, 255, 255));
        ImageJLable.setSize(new java.awt.Dimension(50, 50));

        jLabel24.setText("Nation:");

        jLabel25.setText("Skills:");

        jLabel26.setText("Level:");

        jLabel27.setText("Skills:");

        jLabel28.setText("Level:");

        javax.swing.GroupLayout ViewCoverPanelLayout = new javax.swing.GroupLayout(ViewCoverPanel);
        ViewCoverPanel.setLayout(ViewCoverPanelLayout);
        ViewCoverPanelLayout.setHorizontalGroup(
            ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FnameTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(AffilTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(GenderTextF)
                            .addComponent(NationTextF))
                        .addGap(14, 14, 14)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                        .addComponent(DateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(MonthTextF)
                                            .addComponent(YearTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DegreeTextF)
                            .addComponent(StartTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MajorTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(Skill_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel22))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(Skill_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel28))
                            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                                .addGap(430, 430, 430)
                                .addComponent(Level_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewCoverPanelLayout.createSequentialGroup()
                                    .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CountryTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                    .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewCoverPanelLayout.createSequentialGroup()
                                    .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(AddressTextF)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewCoverPanelLayout.createSequentialGroup()
                                            .addGap(118, 118, 118)
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 67, Short.MAX_VALUE)))
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addComponent(Skill_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel26))
                        .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                            .addGap(430, 430, 430)
                            .addComponent(Level_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Level_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        ViewCoverPanelLayout.setVerticalGroup(
            ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ImageJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewCoverPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(LnameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(YearTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(GenderTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MonthTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(NationTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(AffilTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(MobileTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(EmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(AptTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(CityTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(ZipTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(MajorTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DegreeTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(StartTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(EndTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Skill_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(Level_1TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Skill_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(Level_2TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewCoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Skill_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(Level_3TextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(ViewCoverPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FnameTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameTextFActionPerformed

    private void LnameTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTextFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextF;
    private javax.swing.JTextField AffilTextF;
    private javax.swing.JTextField AptTextF;
    private javax.swing.JTextField CityTextF;
    private javax.swing.JTextField CountryTextF;
    private javax.swing.JTextField DateTextF;
    private javax.swing.JTextField DegreeTextF;
    private javax.swing.JTextField EmailTextF;
    private javax.swing.JTextField EndTextF;
    private javax.swing.JTextField FnameTextF;
    private javax.swing.JTextField GenderTextF;
    private javax.swing.JLabel ImageJLable;
    private javax.swing.JTextField Level_1TextF;
    private javax.swing.JTextField Level_2TextF;
    private javax.swing.JTextField Level_3TextF;
    private javax.swing.JTextField LnameTextF;
    private javax.swing.JTextField MajorTextF;
    private javax.swing.JTextField MobileTextF;
    private javax.swing.JTextField MonthTextF;
    private javax.swing.JTextField NationTextF;
    private javax.swing.JTextField Skill_1TextF;
    private javax.swing.JTextField Skill_2TextF;
    private javax.swing.JTextField Skill_3TextF;
    private javax.swing.JTextField StartTextF;
    private javax.swing.JTextArea StatementTextArea;
    private javax.swing.JPanel ViewCoverPanel;
    private javax.swing.JTextField YearTextF;
    private javax.swing.JTextField ZipTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
