/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendorInterface;

import Bussiness.Product;
import Bussiness.ProductDirectory;
import java.awt.CardLayout;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eric
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel processJPanel;
    private ProductDirectory productDirectory;
    
    public CreateJPanel(JPanel processJPanel, ProductDirectory productDirectory) {
        initComponents();
        this.processJPanel = processJPanel;
        this.productDirectory = productDirectory;
        
        setTime();
    }

    public void setTime(){
        long lon = System.currentTimeMillis();//得到long类型当前时间
        Date date = new Date(lon);//new日期对象
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//转换提日期输出格式
        
        TimeTextF.setText(dateFormat.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TypeBox = new javax.swing.JComboBox<>();
        NameTextF = new javax.swing.JTextField();
        ModelTextF = new javax.swing.JTextField();
        VendorBox = new javax.swing.JComboBox<>();
        DescriptionTextF = new javax.swing.JTextField();
        BasePriceTextF = new javax.swing.JTextField();
        CeilingPriceTextF = new javax.swing.JTextField();
        FloorPriceTextF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FeatureTextA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BenefitTextA = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        TimeTextF = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        jLabel1.setText("Add New Product");

        jLabel2.setText("Product Type :");

        jLabel3.setText("Product Name :");

        jLabel4.setText("Model Number :");

        jLabel5.setText("Vendor :");

        jLabel6.setText("Description :");

        jLabel7.setText("Base Price :");

        jLabel8.setText("Ceiling Price :");

        jLabel9.setText("Floor Price :");

        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Computer", "Printer", "Hardware parts", "Software products" }));

        VendorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "HP", "Dell", "Acer", "ASUS", "Lenovo", "Apple", "ROG", "Microsoft" }));

        jLabel10.setText("Feature :");

        FeatureTextA.setColumns(20);
        FeatureTextA.setRows(5);
        jScrollPane2.setViewportView(FeatureTextA);

        jLabel11.setText("Benefit :");

        BenefitTextA.setColumns(20);
        BenefitTextA.setRows(5);
        jScrollPane3.setViewportView(BenefitTextA);

        jLabel12.setText("Create Time :");

        TimeTextF.setEnabled(false);

        AddBtn.setText("Add Product");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("<Back");
        BackBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        BackBtn.setSize(new java.awt.Dimension(80, 29));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModelTextF)
                    .addComponent(NameTextF)
                    .addComponent(TypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VendorBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DescriptionTextF)
                    .addComponent(BasePriceTextF)
                    .addComponent(CeilingPriceTextF)
                    .addComponent(FloorPriceTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimeTextF))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ModelTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(VendorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(DescriptionTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(BasePriceTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CeilingPriceTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(FloorPriceTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TimeTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        processJPanel.remove(this);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.previous(processJPanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(TypeBox.getSelectedItem().equals("Select...")){
                JOptionPane.showMessageDialog(null, "Please Select Product Type!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(NameTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Name!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(ModelTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Model Number!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(VendorBox.getSelectedItem().equals("Select...")){
                JOptionPane.showMessageDialog(null, "Please Select Product Vendor!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(DescriptionTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Description!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(BasePriceTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Base Price!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(CeilingPriceTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Ciling Price!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(FloorPriceTextF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Insert Product Floor Price!", "Warning", JOptionPane.WARNING_MESSAGE);
            }else{
                String type = String.valueOf(TypeBox.getSelectedItem());
                String name = NameTextF.getText();
                String modelNumber = ModelTextF.getText();
                String vendor = String.valueOf(VendorBox.getSelectedItem());
                String description = DescriptionTextF.getText();
                int basePrice = Integer.parseInt(BasePriceTextF.getText());
                int ceilingPrice = Integer.parseInt(CeilingPriceTextF.getText());
                int floorPrice = Integer.parseInt(FloorPriceTextF.getText());
                String feature = FeatureTextA.getText();
                String benefit = BenefitTextA.getText();
                String date = TimeTextF.getText();
                
                Product product = productDirectory.addProduct();
                
                product.setType(type);
                product.setName(name);
                product.setModelNumber(modelNumber);
                product.setVendor(vendor);
                product.setDescription(description);
                product.setBasePrice(basePrice);
                product.setCeilingPrice(ceilingPrice);
                product.setFloorPrice(floorPrice);
                product.setFeature(feature);
                product.setBenefit(benefit);
                product.setCreateOn(date);
                
                JOptionPane.showMessageDialog(null, "Product Add Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
                
                NameTextF.setText("");
                ModelTextF.setText("");
                DescriptionTextF.setText("");
                BasePriceTextF.setText("");
                CeilingPriceTextF.setText("");
                FloorPriceTextF.setText("");
                FeatureTextA.setText("");
                BenefitTextA.setText("");
                
                setTime();
            }
        }catch(NumberFormatException numex){
            JOptionPane.showMessageDialog(null, "Correct format reuired!", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField BasePriceTextF;
    private javax.swing.JTextArea BenefitTextA;
    private javax.swing.JTextField CeilingPriceTextF;
    private javax.swing.JTextField DescriptionTextF;
    private javax.swing.JTextArea FeatureTextA;
    private javax.swing.JTextField FloorPriceTextF;
    private javax.swing.JTextField ModelTextF;
    private javax.swing.JTextField NameTextF;
    private javax.swing.JTextField TimeTextF;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JComboBox<String> VendorBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
