/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendorInterface;

import vendorInterface.CreateJPanel;
import Bussiness.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Eric
 */
public class ManageAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel processJPanel;
    private ProductDirectory productDirectory;
    
    public ManageAreaJPanel(JPanel processJPanel, ProductDirectory productDirectory) {
        initComponents();
        this.processJPanel = processJPanel;
        this.productDirectory = productDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CatalogBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();

        CatalogBtn.setText("View Product Catalog");
        CatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogBtnActionPerformed(evt);
            }
        });

        AddBtn.setText("Add New Product");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(CatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogBtnActionPerformed
        // TODO add your handling code here:
        ManageJPanel managejp = new ManageJPanel(processJPanel , productDirectory);
        processJPanel.add("ManageJPanel" , managejp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_CatalogBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        CreateJPanel createjp = new CreateJPanel(processJPanel , productDirectory);
        processJPanel.add("CreateJPanel" , createjp);
        CardLayout layout = (CardLayout)processJPanel.getLayout();
        layout.next(processJPanel); 
    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton CatalogBtn;
    // End of variables declaration//GEN-END:variables
}
