/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.admin;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Eric
 */
public class AdminWorkAreaJP extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkArea
     */
    private JPanel processContainer;
    private Business business;
    
    public AdminWorkAreaJP(JPanel processContainer , Business business) {
        initComponents();
        this.processContainer = processContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageEmployeeBtn = new javax.swing.JButton();
        ManageUserAccountBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ManageUserAccountBtn1 = new javax.swing.JButton();

        ManageEmployeeBtn.setText("Manage Employee");
        ManageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployeeBtnActionPerformed(evt);
            }
        });

        ManageUserAccountBtn.setText("Manage User Accounts");
        ManageUserAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserAccountBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Admin Work Area");

        ManageUserAccountBtn1.setText("Manage User Accounts");
        ManageUserAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserAccountBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageUserAccountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageUserAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(ManageEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(ManageUserAccountBtn)
                .addGap(18, 18, 18)
                .addComponent(ManageUserAccountBtn1)
                .addContainerGap(382, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployeeBtnActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJP mejp = new ManageEmployeeJP(processContainer , business);
        processContainer.add("ManageEmployeeJP" , mejp);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_ManageEmployeeBtnActionPerformed

    private void ManageUserAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserAccountBtnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJP muajp = new ManageUserAccountJP(processContainer , business);
        processContainer.add("ManageUserAccountJP" , muajp);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.next(processContainer);
    }//GEN-LAST:event_ManageUserAccountBtnActionPerformed

    private void ManageUserAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserAccountBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageUserAccountBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEmployeeBtn;
    private javax.swing.JButton ManageUserAccountBtn;
    private javax.swing.JButton ManageUserAccountBtn1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
